Siemens-Healthineers/K2s

smallsetup/helpers/ImageFunctions.module.psm1

Path is not always up to date in test szenarios, crictl is not found always
Added path in crictl calls for local calls
Checked within a powershell test

#47 Adding path for local execution

---

lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/distros/ubuntu/ExistingUbuntuComputerAsMasterNodeInstaller.ps1
smallsetup/InstallK8s.ps1
smallsetup/linuxnode/linuxnode.module.psm1
smallsetup/linuxnode/linuxnode.module.unit.tests.ps1
smallsetup/linuxnode/ubuntu/ExistingUbuntuComputerAsMasterNodeInstaller.ps1
smallsetup/linuxnode/ubuntu/ExistingUbuntuComputerAsMasterNodeInstaller.unit.tests.ps1

Fixes the installation of the control plane in a running VM with Ubuntu.
The installation was broken due to a mismatching parameter name and the usage of a not superseded method.
1. Created a VM with Ubuntu Desktop 22.04
2. Created a Virtual Switch to connect the Windows Host with the VM
3. Installed the ssh server on the VM
4. Called the script ".\smallsetup\InstallK8s.ps1 -ShowLogs -LinuxVMIP '_the IP_' -LinuxVMUsername '_the user name_' -LinuxVMUserPwd '_the user password_'"

Fixed control plane installation on VM with Ubuntu (#39)

---

lib/modules/k2s/k2s.cluster.module/image/image.module.psm1

Missing path in crictl call
All exe calls shall have direct path before
Tested through powershell

#47 Fix location handling in lib

---

addons/Export.ps1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/downloader.module.psm1
smallsetup/windowsnode/downloader/DownloadWindowsImages.ps1

Fixes issue #71 
Nerdctl now pulls all layers for windows images
Changed option to pull all layers
Tested with CI workflow on windows 11

Windows 11 changes breaks the k2s install

---

.github/workflows/ci-unit-tests.yml

Bump setup-go to v5 to fix slow cache copy

Bump setup-go to v5 to fix slow cache copy

---

pkg/k2s/README.md

Adapted path to bgo.cmd in the k2s readme file (\<installation folder\>\pkg\k2s\README.md)

Fix: corrected documented path to bgo.cmd

---

.github/workflows/build-k2s-cli.yml

The following changes were done:
- Single job 
- Job first builds the cli on the runnner
- Job runs the acceptance with the built cli in the runner
- If the acceptance tests are successful, then the job commits the built k2s cli
- During the commit, the job provides "skip_checks: true" to merge directly to main branch with waiting for unit tests results

Adaptations for build k2s cli workflow when branch protection rules are activated

---

smallsetup/multivm/Install_MultiVMK8sSetup.ps1

#119 
The download target argument for kubectl.exe contained a not needed '&' sign at the beginning.

Removed not needed '&' in download target argument (#119)

---

addons/exthttpaccess/Enable.ps1
addons/exthttpaccess/addon.manifest.yaml
test/e2e/addons/exthttpaccess/exthttpsaccess_test.go

#88 
In the exthttpaccess addon the flag `--force-use-alternative-ports-if-needed` (shortcut '`-f`') was changed to `--autoconfirm-alt-ports` (shortcut '`-a`')

Changed flag name for autoconfirmation of use of alternative ports in addon 'exthttpaccess'

---

smallsetup/linuxnode/linuxnode.module.unit.tests.ps1

**Root cause:**
In production the module `'linuxnode.module.psm1'` works together with one of the following specialization modules 
- `linuxnode.debian.module.psm1`
- `linuxnode.ubuntu.module.psm1`
by calling the methods
`Set-UpComputerWithSpecificOsBeforeProvisioning`
`Set-UpComputerWithSpecificOsAfterProvisioning`
that are implemented in the specialization modules.
Since the test suite is tested in isolation those methods are not present.
**Solution:**
Define the methods in the test suite to satisfy the dependency.

Fix for test suite 'New-KubernetesNode'

---

test/e2e/cli/cmd/image/setuprequired/systemrunning/image_system-running_test.go

Fix Linuxonly tests failing because of reset win storage test

Fix Linuxonly tests failing because of reset win storage test

---

pkg/k2s/utils/logging/logbuffer.go
pkg/k2s/utils/logging/logging_test.go
pkg/k2s/utils/psexecutor/psexecutor.go

#29 refactor([CLI] psexecutor): lines from stderr stream are buffered up to a max before getting flushed to file

---

pkg/k2s/cmd/image/resetwinstorage.go
smallsetup/helpers/CleanupContainerStorage.ps1
smallsetup/helpers/ResetWinContainerStorage.ps1
smallsetup/windowsnode/publisher/PublishWindowsImages.ps1

- Redirected all logs from icacls and takeown commands to k2s cli log so it is possible to determine which files/folders could not deleted.
- The command by default asks for user confirmation before triggering this operation. The prompt can be bypassed by providing the ***-f*** or ***--force*** options.
- The force-zap flag has now a new shorthand ***-z*** as ***-f*** is now used by force.

Improved reset-win-storage output

---

README.md
doc/K8s_Get-K2s.md

Fixes https://github.com/Siemens-Healthineers/K2s/issues/367
When following the Quickstart in README.md, users miss to unblock the downloaded ZIP file and run into problems.
- README.md links now to the "How to Get" instructions, where the procedure is described in detail
- The link to the Releases in How to Get was broken, and is now pointing to the Releases
n.a.

fixes https://github.com/Siemens-Healthineers/K2s/issues/367

---

smallsetup/InstallK8s.ps1
smallsetup/ps-modules/only-while-refactoring/installation/still-to-merge.path.module.psm1

A temporary module was created to set the environment paths and is used in the InstallK8s.ps1 script.
The current available module could not be used since it has equally named methods as the file GlobalFunctions.ps1 thus leading to superseeding effects. Once the file GlobalFunctions.ps1 is not called anymore from InstallK8s.ps1 the usage of the temporary module will be discontinued.

#348 refactor(install): Uses module to set environment paths

---

smallsetup/InstallK8s.ps1

Uses the existing method in the system module to add k2s to the defender exclusion.

#348 refactor(install): Uses existing system module to add k2s to defender exclusion

---

smallsetup/InstallK8s.ps1

Uses the existing system module to check if docker desktop is installed on the Windows host where the installation will be done.

#348 refactor(install): Uses the system module to check if docker destop is installed

---

smallsetup/InstallK8s.ps1
smallsetup/ps-modules/only-while-refactoring/installation/still-to-merge.path.module.psm1

Uses the temporary added path module to get the installation path. The existing path module was not used because it was not referenced in InstallK8s.ps1 and adding its reference would have superseeded methods in GlobalFunctions.ps1 that are not in relation with the intended change.

#348 refactor(install): Uses temporary added path module to get the installation path

---

smallsetup/InstallK8s.ps1
smallsetup/ps-modules/only-while-refactoring/installation/still-to-merge.config.module.psm1

A temporary module was created to get the kubernetes version and is used in the InstallK8s.ps1 script.
The current available module could not be used since it has equally named methods as the file GlobalFunctions.ps1 thus leading to superseeding effects. Once the file GlobalFunctions.ps1 is not called anymore from InstallK8s.ps1 the usage of the temporary module will be discontinued.

#348 refactor(install): Uses module to get the kubernetes version

---

smallsetup/InstallK8s.ps1
smallsetup/ps-modules/only-while-refactoring/installation/still-to-merge.vm.module.psm1

The name for the control plane VM is not retrieved from GlobalVariables.ps1 anymore but from a module.

#348 refactor(install): Uses module to retrieve the name of the control plane VM

---

smallsetup/InstallK8s.ps1
smallsetup/ps-modules/only-while-refactoring/installation/still-to-merge.config.module.psm1
smallsetup/ps-modules/only-while-refactoring/installation/still-to-merge.loopbackadapter.module.psm1
smallsetup/ps-modules/only-while-refactoring/installation/still-to-merge.path.module.psm1
smallsetup/ps-modules/only-while-refactoring/installation/still-to-merge.windowsnode.module.psm1

2 temporary modules were created to retrieve the values provided by the directly used global variables and are used in the InstallK8s.ps1 script.
The current available modules could not be used since they have equally named methods as the file GlobalFunctions.ps1 thus leading to superseeding effects. Once the file GlobalFunctions.ps1 is not called anymore from InstallK8s.ps1 the usage of the temporary modules will be discontinued.

#348 refactor(install): Replaces direct usage of global variables with values retrieved from modules.

---

smallsetup/InstallK8s.ps1
smallsetup/UninstallK8s.ps1
smallsetup/ps-modules/only-while-refactoring/installation/still-to-merge.isolatedcalledscripts.module.psm1

The scripts StartK8s.ps1 and StopK8s.ps1 do not use GlobalVariables.ps1 nor GlobalFunctions.ps1 anymore, therefore the call to them from InstallK8s.ps1 through the isolation module has been removed and are called directly again.

#348 refactor(install): Removes calls to StartK8s.ps1 and StopK8s.ps1 through isolation module

---

lib/modules/k2s/k2s.node.module/linuxnode/network/network.module.psm1
lib/scripts/multivm/start/Start.ps1
smallsetup/StartK8s.ps1
smallsetup/common/GlobalFunctions.ps1

Fixes #466
See Issue #466 
Disables the "Register this Connections IP Address on the DNS" when enabling the loopback adapter.
To do...

disable dns registration for loopback

---

addons/dashboard/manifests/dashboard-nginx-ingress.yaml
addons/dashboard/manifests/dashboard-traefik-ingress.yaml
addons/ingress-nginx/Enable.ps1
addons/ingress-nginx/README.md
addons/ingress-nginx/manifests/cluster-net-ingress.yaml
addons/logging/Enable.ps1
addons/logging/logging.module.psm1
addons/logging/manifests/opensearch-dashboards/deployment.yaml
addons/logging/manifests/opensearch-dashboards/ingress.yaml
addons/logging/manifests/opensearch-dashboards/kustomization.yaml
addons/logging/manifests/opensearch-dashboards/traefik.yaml
addons/monitoring/Enable.ps1
addons/monitoring/manifests/plutono/configmap.yaml
addons/monitoring/manifests/plutono/ingress.yaml
addons/monitoring/manifests/plutono/kustomization.yaml
addons/monitoring/manifests/plutono/traefik.yaml
addons/monitoring/monitoring.module.psm1
addons/security/Disable.ps1
addons/security/Enable.ps1
addons/security/security.module.psm1
addons/traefik/Enable.ps1
addons/traefik/README.md
addons/traefik/manifests/cluster-net-ingress.yaml
k2s/test/e2e/addons/dashboard/dashboard_test.go
k2s/test/e2e/addons/ingress-nginx/ingress-nginx_test.go
k2s/test/e2e/addons/logging/logging_test.go
k2s/test/e2e/addons/monitoring/monitoring_test.go
k2s/test/e2e/addons/security/security_test.go
k2s/test/e2e/addons/traefik/traefik_test.go

This is part of the feature **#258: New addon security for the K2s cluster** and is addressing the TLS termination at Ingress (both: NGINX and Traefik)
This PR makes it possible for more web applications hosted on K2s to shall share one common ingress host, and expose their functionality under relative paths: `k2s.cluster.net`
Both `ingress-nginx` and `traefik` addons come now with a central TLS Ingress with no paths, but with a tls entry matching the mentioned hostname.
All Web UIs of our AddOns contain now a second ingress route, which is merged with the central one, so that each UI is now available under 3 URLs:
- Dashboard:  
http://k2s-dashboard.local
https://k2s-dashboard.local
**new:** https://k2s.cluster.net/dashboard/
- Logging:
http://k2s-logging.local
https://k2s-logging.local …

central ingress tls

---

k2s/test/e2e/addons/dashboard/dashboard_test.go

add retry-all-errors in curl command for dashboard tests

add retry-all-errors in curl command for dashboard tests

---

k2s/cmd/k2s/cmd/image/build.go
k2s/cmd/k2s/cmd/image/clean.go
k2s/cmd/k2s/cmd/image/export.go
k2s/cmd/k2s/cmd/image/import.go
k2s/cmd/k2s/cmd/image/import_test.go
k2s/cmd/k2s/cmd/image/pull.go
k2s/cmd/k2s/cmd/image/registry/add.go
k2s/cmd/k2s/cmd/image/registry/switch.go
k2s/cmd/k2s/cmd/image/remove.go

#457 fix(multivm image CMDs): erroneous commands disabled

---

addons/security/Enable.ps1
addons/security/security.module.psm1

Fixes #TODO
Part of [security addon feature](https://github.com/Siemens-Healthineers/K2s/issues/258):  
When the add-on is enabled, cert-manager is now requested to renew all certificates,
using the new CA Issuer. This is needed for situations when the security addon was disabled,
leaving valid certificates in use - but the CA Issuer is removed from the computers trusted root certificates.
Re-enabling the plugin creates a new CA Issuer, imports this one in the trusted root - so the old certificates 
must all be renewed.
Invoke this after CA Issuer is created:
```script
cmctl.exe renew -all -all-namespaces
```
manual tests

renew old certificates when security addon is enabled

---

k2s/cmd/k2s/cmd/system/reset/reset.go
k2s/cmd/k2s/cmd/system/scp/scp.go
k2s/cmd/k2s/cmd/system/upgrade/upgrade.go

#457 fix(multivm system CMDs): erroneous commands disabled

---

lib/modules/k2s/k2s.node.module/windowsnode/network/network.module.psm1

* Only the mandatory services or critical ones should be shown to the user. Rest of them to the files.
* Also, nlasvc is not relevant for the user from a cluster point of view.

Chore(log): File logging is sufficient for nlasvc restart

---

addons/README.md
addons/gateway-nginx/addon.manifest.yaml

gateway-nginx was already stable but docs were misleading. Fixed them.

fix(docs): gateway-nginx no longer experimental

---

addons/security/Enable.ps1
k2s/test/e2e/addons/security/security_test.go

An Ingress controller is pre-requisite for security addon, so enabling default one if not present.
Adapted e2e test as well.

#258 feat(security): provide default ingress when missing

---

lib/modules/k2s/k2s.node.module/linuxnode/setup/control-plane-node.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/new-hyperv-vm-as-linuxnode.module.psm1

The value of the flag '-f' is passed through to the place where it is decided:
- if the zip file with the Windows node artifacts has to be created
- if the file Kubenode-Base.vhdx has to be created

#348 refactor(install): Fixes force online installation

---

lib/modules/k2s/k2s.node.module/windowsnode/services/services.module.psm1

Done by importing the module k2s.infra.module.psm1 into the module that calls the function 'Get-KubeBinPath'

fix(image pull): Fixes lookup of function 'Get-KubeBinPath'

---

k2s/cmd/k2s/cmd/common/common.go
k2s/cmd/k2s/cmd/image/resetwinstorage.go
k2s/cmd/k2s/cmd/image/resetwinstorage_test.go

Fixed implementation of reset-win-storage to let it execute even when k2s is not installed.
This is required to address the usecase that the user may want to clean up docker and containerd directories when the user has uninstalled k2s.
Similarly, reset-win-storage command must be executed when k2s is in corrupted state.
Added unit tests to validate that the reset-win-storage command is executed even when k2s is uninstalled or in corrupted state.

fix(607): remove uninstall check from reset-win-storage command

---

k2s/test/e2e/cli/cmd/image/nosetup/corruptedstate/image_corrupted-state_test.go

fixed corrupted-state image tests for reset-win-storage command

fix: fix corrupted state tests for reset-win-storage command

---

addons/traefik/Enable.ps1
addons/traefik/manifests/deployment.yaml

Fixes the hard-coded ingressEndpoint in traefik deyploment file
traefik manifests was containing hardcoded IP address of the control plane, which is not the same in all deployments.
The IP Address is set now during enabling of the addon
n.a.

fix(traefik): ingressEndpoint set dynamically

---

k2s/cmd/k2s/main.go

Dump stack to user only when there is a panic in golang. Removed critical error message.

feat(cli): removed critical error msg and dump stack only during panic

---

k2s/cmd/k2s/cmd/common/common.go
k2s/cmd/k2s/cmd/install/core/installer.go
k2s/cmd/k2s/cmd/install/core/installer_test.go
k2s/cmd/k2s/cmd/install/install.go

There are two categories of failures during install
1. Pre-requisites failure ---> does not lead to corrupted state, uninstall is not necessary, cleanup of setup.json done.
2. Installation failure --> leads to corrupted state, uninstall is required.

feat(install): distinction of pre-req and install failure

---

k2s/cmd/k2s/cmd/uninstall/uninstall.go

This handles scenario when setuptype is invalid then proceed with default variant 'k2s' uninstall which cleans up the invalid setup.json as well. Then user is not blocked with install and uninstall cycle.

feat(uninstall): default uninstall when setup is invalid

---

k2s/test/e2e/cli/cmd/system/nosetup/system_no-setup_test.go

- Adapted system dump acceptance test which can now run without k2s installed.

feat(dump): adapted acceptance tests

---

lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/network/network.module.psm1
smallsetup/StartK8s.ps1

Re-implemented Vswitch caching feature after refactoring changes
Merging the following [PR](https://github.com/Siemens-Healthineers/K2s/pull/657) from Main into release-1.1.x
Some reimplementation was needed as Main has more refactored code than the release branch

fix: fixed vswitch caching

---

lib/modules/k2s/k2s.node.module/linuxnode/baseimage/provisioning.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1

Install Zscaler certificate to KubeNode_IN_Provisioning VM
To avoid getting errors during image pull
Made changes to Common-setup.module.psm1 file.
Verified locally that the certificate is getting added to "KubeNode_In_Provisioning" VM.

Zscaler provision node certificate installation

---

lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/docker/docker.module.psm1

Removed renaming of docker config as this operation conflicts with nerdctl login. Also, docker install is ad-hoc, so changing config at this point will lead to inconsistent configs.

fix(docker): consistent config across container runtimes

---

lib/modules/k2s/k2s.infra.module/config/config.module.psm1

Provide default value when config is not set. Without default value, observed errors during start and stop of the cluster and leads to inconsistent state.

fix(wsl): provide default value

---

k2s/cmd/k2s/cmd/uninstall/uninstall.go

#796
Merges the changes from #506 for falling back to the 'default variant' setup type in case the setup type cannot be determined during uninstallation.

fix(uninstall): falls back to default variant

---

lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/control-plane-node.module.psm1

Install Zscaler certificate on first VM that we create during the installation of K2s
To avoid failures while downloading the needed images.
Made changes in "Install-KubernetesArtifacts" of "common-setup.module.psm1" to install the Zscaler certificate.
Removed changes from "New-ControlPlaneNodeOnNewVM" of "control-plane-node.module.psm1" that installed the Zscaler certificate directly on KubeMaster.
1.Tested by installing the K2s locally and made sure that the certificate is installed in Kubemaster. 
2. Also the installation of k2s with Debian 12 OS went through when Zscaler was enabled.

Adding Zscaler cert to provisioning VM : Issue #630

---

smallsetup/ps-modules/proxy/proxy.module.psm1

Added the missing methods in the old proxy module to fix linux-only, multi-vm and build-only installations

fix: add missing methods in old module

---

lib/modules/k2s/k2s.node.module/windowsnode/proxy/proxy.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/system/system.module.psm1
smallsetup/common/GlobalFunctions.ps1
smallsetup/ps-modules/proxy/proxy.module.psm1

If NO_PROXY variable is set then all k2s subnets and hosts are added to it during installation. They are removed on uninstallation

fix: add all k2s hosts during install

---

lib/modules/k2s/k2s.node.module/linuxnode/setup/worker-node.module.psm1

#39 
Since the service 'ufw' is disabled on the Linux node being added to the cluster, the calls to allow the ports used by kubernetes are not needed.

feat(node): removes ufw calls

---

k2s/test/e2e/addons/generic/build_image/build_image_test.go

Enable ingress for registry access as default ingress option is not valid anymore.

fix(build-image-e2e): enable ingress nginx

---

lib/modules/k2s/k2s.node.module/linuxnode/setup/control-plane-node.module.psm1

Reintroduce the deletion of pwd access into the VM acting as control plane after its installation.

refactor(install): reintroduce no pwd access to control plane

---

docs/op-manual/adding-k2s-users.md
docs/op-manual/extending-k2s-cluster.md
k2s/internal/core/node/ssh/ssh.go
k2s/internal/core/node/ssh/ssh_test.go
k2s/test/e2e/cli/cmd/node/setuprequired/systemrunning/copy/copy_system-running_test.go
k2s/test/e2e/cli/cmd/system/setuprequired/systemrunning/users/users_systemrunning_test.go
lib/modules/k2s/k2s.infra.module/config/config.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/security/security.module.psm1
smallsetup/common/GlobalVariables.ps1

#39 
Renamed the folder where the k2s ssh key pair is located from "%USERPROFILE%\\.ssh\kubemaster" to "%USERPROFILE%\\.ssh\k2s"

feat(node): renamed ssh keys folder

---

.gitignore
lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/worker-node.module.psm1
lib/scripts/k2s/system/package/New-LinuxNodeArtifactsPackage.ps1

#39 
Added the script `.\lib\scripts\k2s\system\package\New-LinuxNodeArtifactsPackage.ps1` to create the file `.\bin\LinuxNodeArtifacts.zip` that contains the content of the folder `.\bin\linuxnode` where the deb packages and container images are located for setting up kubernetes in offline mode in a new Linux node.
The folder `.\bin\linuxnode` contains two subfolders:
- `packages` contains distribution specific deb packages separated in subfolders named according to the distribution name and version.
- `images` contains container images.
The logic populates the above mentioned folders with artifacts taken from the Control Plane VM (i.e. KubeMaster) if they are not present in the file system, otherwise their content will not be overwritten.
This Pull Request also adds the logic to use the …

feat(node): Linux offline package

---

lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/system/system.module.psm1

Fixes #907 
If K2s is installed with `--wsl`, the `dnsmasq` service cannot be started because `port 53` is already in use
Disable the following options in the .wslconfig file of the user:
```cmd
localhostForwarding=false
dnsProxy=false
dnsTunneling=false
```
Existing WSL tests are passing

#907: fixes issue of dnsmasq not being available in wsl mode

---

lib/modules/k2s/k2s.cluster.module/setup/setupcluster.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/baseimage/NetplanK2s.yaml
lib/modules/k2s/k2s.node.module/linuxnode/baseimage/base-image.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/baseimage/cloud-init-templates/network-config
lib/modules/k2s/k2s.node.module/linuxnode/baseimage/cloud-init-templates/user-data
lib/modules/k2s/k2s.node.module/linuxnode/baseimage/provisioning.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/control-plane-node.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/worker-node.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1

[Fixes #TODO](https://github.com/Siemens-Healthineers/K2s/issues/649)
Upgrade to Debian 12 as Debian 11 would reach EOL soon.
1. lib/modules/k2s/k2s.cluster.module/setup/setupcluster.module.psm1 --> Start crio explicitly as it takes time to get started on VM reboot.
2. lib/modules/k2s/k2s.node.module/linuxnode/baseimage/NetplanK2s.yaml --> New Netplan configuration file with required parameters.
3. lib/modules/k2s/k2s.node.module/linuxnode/baseimage/base-image.module.psm1 --> Using new Linux12 OS instead of Linux 11 and had to specify the subnet additionally, if not the IP address would not be set for the VM created.
4. lib/modules/k2s/k2s.node.module/linuxnode/baseimage/cloud-init-templates/network-config --> Adapting to newer configuration.
5. …

Consolidated Debian Changes

---

lib/modules/k2s/k2s.node.module/linuxnode/baseimage/cloud-init-templates/user-data

In some test runs, we discovered that the PasswordAuthentication was set to no, when the linux virtual machine was provisioned for the first time. This causes ssh authentication parts to fail. Now during cloud-init, we enable this explicitly.

fix: enable password auth explicitly in cloud-init
