Siemens-Healthineers/K2s

.github/workflows/ci.yml

Setup CI Pipeline
Add pipelines for building artifacts.

Show git diff during ci

---

.github/workflows/ci.yml

setup k2s continuous integration pipeline

---

.github/workflows/build-k2s-cli.yml
.github/workflows/ci.yml

Pull latest from main

---

.github/workflows/build-k2s-cli.yml
pkg/k2s/README.md

- Added name for pipeline build k2s cli
- test change under pkg to trigger pipeline

8-setup-k2s-continuous-integration-pipeline

---

.github/workflows/build-k2s-cli.yml

remove go mod download temporarily

remove go mod download temporarily

---

.github/workflows/build-k2s-cli.yml

Enabled manual trigger for k2s build pipeline

Enabled manual trigger for k2s build pipeline

---

smallsetup/common/vmtools/InstallWindowsVM.ps1

Cleanup shares and corrected git repo

Cleanup win vm

---

lib/modules/k2s/k2s.cluster.module/setup/setupcluster.module.psm1
lib/modules/k2s/k2s.multivm.module/multivm/multivm.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/downloader.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/system/system.module.psm1
lib/scripts/k2s/install/Install.ps1
lib/scripts/multivm/install/Install.ps1

Added steps for windows vm node

Added steps for windows vm node

---

README.md
doc/K8s_BuildOnly.md
doc/K8s_Get-K2s.md
doc/K8s_K2sCli.md
doc/K8s_Upgrade.md

Broken links in documentation
Links shall be intact
Checked with preview in code

Documentation links broken #50

---

addons/Export.ps1
lib/scripts/k2s/image/Pull-Image.ps1
smallsetup/helpers/PullImage.ps1

Still missing calls of crictl without path
Fixed locations in export of addons
Thorugh direct powershell calls

#47 Fix for other locations of crictl call

---

lib/modules/k2s/k2s.cluster.module/setup/setupcluster.module.psm1
lib/modules/k2s/k2s.infra.module/config/config.module.psm1
lib/modules/k2s/k2s.multivm.module/multivm/multivm.module.psm1
lib/modules/k2s/k2s.node.module/vmnode/vmnode.module.psm1
lib/scripts/multivm/install/Install.ps1

vm based cluster init

---

README.md
doc/K8s_AddRegistry.md
doc/K8s_BuildOnly.md
doc/K8s_Get-K2s.md
doc/K8s_K2sCli.md
doc/K8s_Trainings.md
doc/K8s_Troubleshoot.md

Wrong entries in documentation
Positions corrected
Preview in studio code

Documentation corrections

---

lib/modules/k2s/k2s.multivm.module/multivm/multivm.module.psm1

sync node with host source

---

smallsetup/multivm/Uninstall_MultiVMK8sSetup.ps1

cleanup of helm reference

---

lib/modules/k2s/k2s.cluster.module/image/image.module.psm1
lib/modules/k2s/k2s.multivm.module/multivm/multivm.module.psm1

write images for windows node vm

write images for windows node vm

---

lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1

fix for missing registry conf

---

lib/modules/k2s/k2s.node.module/linuxnode/setup/setuplinuxnode.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/putty-tools/putty-tools.module.psm1
lib/scripts/multivm/install/Install.ps1

vm as node install complete

---

lib/modules/k2s/k2s.node.module/vmnode/vmnode.module.psm1
lib/scripts/multivm/install/Install.ps1
lib/scripts/multivm/start/Start.ps1
lib/scripts/multivm/stop/Stop.ps1

draft vm node start and stop

---

lib/modules/k2s/k2s.infra.module/config/config.module.psm1
lib/modules/k2s/k2s.node.module/vmnode/vmnode.module.psm1
lib/scripts/k2s/start/Start.ps1
lib/scripts/multivm/install/Install.ps1
lib/scripts/multivm/start/Start.ps1

vm node start complete

---

lib/modules/k2s/k2s.cluster.module/image/image.module.psm1

fix for missing win images

---

addons/addons.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1
smallsetup/common/GlobalFunctions.ps1
smallsetup/linuxnode/linuxnode.module.psm1

Fixes #92 
- Added places where a fix command was specified for correcting state of failure
- Increased timeout to 2 sec to wait longer and be more robust

Improve install stability for network glitches

---

lib/modules/k2s/k2s.cluster.module/system/system.module.psm1
lib/modules/k2s/k2s.node.module/vmnode/vmnode.module.psm1
lib/scripts/multivm/start/Start.ps1
lib/scripts/multivm/stop/Stop.ps1

vm node stop complete

---

lib/modules/k2s/k2s.node.module/linuxnode/setup/setuplinuxnode.module.psm1
lib/modules/k2s/k2s.node.module/vmnode/vmnode.module.psm1
lib/scripts/multivm/uninstall/Uninstall.ps1

vm node uninstall compete

---

lib/modules/k2s/k2s.cluster.module/image/image.module.psm1
lib/modules/k2s/k2s.cluster.module/setup/setupcluster.module.psm1
lib/modules/k2s/k2s.cluster.module/status/status.module.psm1
lib/modules/k2s/k2s.node.module/vmnode/vmnode.module.psm1
lib/scripts/k2s/image/Get-Images.ps1

image cmd for vm based worker node

image cmd for vm based worker node

---

lib/scripts/buildonly/install/Install.ps1

install buildonly draft

---

lib/modules/k2s/k2s.infra.module/config/config.module.psm1
lib/scripts/buildonly/install/Install.ps1
lib/scripts/k2s/install/Install.ps1
lib/scripts/multivm/install/Install.ps1

common version of upstream k8s for all install types

common version of upstream k8s for all install types

---

lib/modules/k2s/k2s.node.module/windowsnode/downloader/downloader.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1

buildonly install complete

---

lib/scripts/buildonly/install/Install.ps1
lib/scripts/buildonly/uninstall/Uninstall.ps1

uninstall buildonly draft

---

pkg/k2s/cmd/reset/network.go
smallsetup/helpers/ResetNetwork.ps1

Add user confirmation to k2s reset network

Add user confirmation to k2s reset network

---

lib/scripts/k2s/image/Get-Images.ps1
pkg/k2s/cmd/image/list.go
test/e2e/cli/cmd/image/nosetup/image_no-setup_test.go
test/e2e/cli/cmd/image/setuprequired/systemstopped/image_system-stopped_test.go
test/framework/k2s/image.go

#79 fix([CLI] image ls): message instead of error when system is stopped

---

test/e2e/cli/cmd/image/nosetup/image_no-setup_test.go

#79 fix(e2e image ls): missing string conversion added

---

lib/scripts/k2s/start/Start.ps1
lib/scripts/multivm/start/Start.ps1
smallsetup/StartK8s.ps1
smallsetup/multivm/Start_MultiVMK8sSetup.ps1

Fix for default switch not available

Fix #109 default switch not available

---

lib/modules/k2s/k2s.node.module/windowsnode/system/system.module.psm1
lib/scripts/buildonly/install/Install.ps1
smallsetup/InstallK8s.ps1
smallsetup/common/GlobalFunctions.ps1

Check for hns and vmcompute services
On install this check is done now
Tested with CI and Windows 10

Add check for mandatory services

---

doc/K8s_Troubleshoot.md

Added workaround for Windows Hyper-V unable to start

feat(doc): Added workaround for Windows Hyper-V unable to start

---

lib/modules/k2s/k2s.node.module/windowsnode/system/system.module.psm1
lib/scripts/buildonly/install/Install.ps1
lib/scripts/k2s/install/Install.ps1
lib/scripts/multivm/install/Install.ps1
smallsetup/InstallK8s.ps1
smallsetup/common/GlobalFunctions.ps1

fixes system restart during install

fixes system restart during install #22

---

pkg/k2s/cmd/image/build_test.go

#40 fix([CLI] image build tests): circumvent Go's map behavior

---

addons/Export.ps1
addons/Import.ps1

- fix addons/Export.ps1
- fix addons/Import.ps1

k2s addons import command deletes source scripts

---

pkg/k2s/cmd/image/export.go
pkg/k2s/cmd/image/export_test.go
pkg/k2s/cmd/image/remove.go
smallsetup/helpers/RemoveImage.ps1
test/e2e/cli/cmd/image/setuprequired/systemstopped/image_system-stopped_test.go

#79 fix([CLI] image rm): message instead of error when system is stopped

---

pkg/k2s/cmd/image/clean.go
smallsetup/helpers/CleanImages.ps1
test/e2e/cli/cmd/image/setuprequired/systemstopped/image_system-stopped_test.go

#79 fix([CLI] image clean): message instead of error when system is stopped

---

.github/workflows/build-k2s-artifacts.yml
.github/workflows/build-k2s-cli.yml
.github/workflows/ci-unit-tests.yml

Reverted usage of skip_checks: true as it did not work
Adapted build-k2s-artifacts workflow same as build k2s cli workflow

120 build k2s cli workflow

---

pkg/k2s/cmd/image/export.go
pkg/k2s/cmd/image/export_test.go
pkg/k2s/cmd/image/import.go
pkg/k2s/cmd/image/import_test.go
smallsetup/helpers/ExportImage.ps1
smallsetup/helpers/ImportImage.ps1
test/e2e/cli/cmd/image/nosetup/image_no-setup_test.go
test/e2e/cli/cmd/image/setuprequired/systemstopped/image_system-stopped_test.go

#79 fix([CLI] image export/import): message instead of error when system is stopped

---

smallsetup/windowsnode/downloader/DownloadWindowsImages.ps1

Fix ctr warnings treated as errors

Fix #137 Ctr warnings are treated as errors

---

pkg/k2s/cmd/common/common.go
pkg/k2s/cmd/common/common_test.go
pkg/k2s/cmd/image/resetwinstorage.go
pkg/k2s/main.go
pkg/k2s/setupinfo/setupinfo_test.go
pkg/k2s/status/status.go
pkg/k2s/status/status_test.go
smallsetup/helpers/ResetWinContainerStorage.ps1
test/e2e/cli/cmd/image/setuprequired/systemrunning/image_system-running_test.go
test/e2e/cli/cmd/image/setuprequired/systemstopped/image_system-stopped_test.go

#79 fix([CLI] image reset-win-storage): message instead of error when system is running

---

lib/modules/k2s/k2s.infra.module/log/log.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1
lib/scripts/buildonly/uninstall/Uninstall.ps1
lib/scripts/k2s/uninstall/Uninstall.ps1
lib/scripts/multivm/uninstall/Uninstall.ps1
smallsetup/UninstallK8s.ps1
smallsetup/common/UninstallBuildOnlySetup.ps1
smallsetup/multivm/Uninstall_MultiVMK8sSetup.ps1
smallsetup/ps-modules/log/log.module.psm1

k2s uninstall k2s cli logs get deleted during uninstall

67 k2s uninstall k2s cli logs get deleted during uninstall

---

lib/modules/k2s/k2s.cluster.module/status/status.module.psm1
lib/modules/k2s/k2s.cluster.module/status/status.module.unit.tests.ps1
pkg/k2s/cmd/status/load/statusLoader.go
pkg/k2s/cmd/status/status.go

Reverts Siemens-Healthineers/K2s#143

Revert "remove addons from k2s status"

---

lib/modules/k2s/k2s.cluster.module/setup/setupcluster.module.psm1
lib/modules/k2s/k2s.infra.module/path/path.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/containerd/containerd.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/downloader.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1
lib/scripts/buildonly/install/Install.ps1

fixes for buildonly install

---

pkg/k2s/cmd/image/registry/add.go
pkg/k2s/cmd/image/registry/list.go
pkg/k2s/cmd/image/registry/switch.go
pkg/k2s/config/config.go
smallsetup/helpers/AddRegistry.ps1
smallsetup/helpers/SwitchRegistry.ps1
test/e2e/cli/cmd/image/setuprequired/image_setup-required_test.go
test/e2e/cli/cmd/image/setuprequired/systemstopped/image_system-stopped_test.go
test/execute_all_tests.ps1
test/test.module.psm1

Image-registry-fix

---

pkg/k2s/cmd/system/ssh/common.go

#148 fix([CLI] system ssh): not-installed case check re-added

---

lib/modules/k2s/k2s.node.module/linuxnode/baseimage/BaseImage.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/system/system.module.psm1
smallsetup/common/GlobalFunctions.ps1

Setting a connection timeout increases stability for downloading files
Testet on machine in test network

Add connection timeout for some use cases

---

test/e2e/cli/cmd/status/nosetup/status_no-setup_test.go

k2s status: Remove Addons' Status

---

lib/modules/k2s/k2s.infra.module/log/log.module.psm1
smallsetup/ps-modules/log/log.module.psm1

ZipArchive helper issue in VMI

ZipArchive helper issue in VMI, first copy then compress

---

lib/scripts/k2s/stop/Stop.ps1
lib/scripts/multivm/stop/Stop.ps1
smallsetup/StopK8s.ps1
smallsetup/multivm/Stop_MultiVMK8sSetup.ps1

[uninstall] check kubectl before setting context

[uninstall] check kubectl before setting context

---

lib/modules/k2s/k2s.cluster.module/setup/setupcluster.module.psm1
smallsetup/common/JoinWindowsHost.ps1

fix Temporary kubeadm not part of Firewall rule

fix Temporary kubeadm not part of Firewall rule #161

---

pkg/k2s/utils/utilities.go

determine installation directory properly

determine installation directory properly

---

test/e2e/cli/cmd/status/setuprequired/systemrunning/status_system-running_test.go

#62 k2s status no longer has addon test adaptation

#62 k2s status addon test adaptation

---

doc/K8s_Troubleshoot.md

docs: added solution for error in hcs::CreateComputeSystem

docs: added solution for error in hcs::CreateComputeSystem

---

pkg/k2s/cmd/addons/addons.go
pkg/k2s/cmd/addons/cmd/list/list.go

refactor k2s addons ls cmd

---

build/bom/merge/k2s-static.json

#128 Added components from addons

#128 Added components from addons

---

smallsetup/helpers/ResetWinContainerStorage.ps1
test/e2e/cli/cmd/image/setuprequired/systemrunning/image_system-running_test.go

extend reset win container storage test

extend reset win container storage test

---

lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1
smallsetup/UninstallK8s.ps1

Missing cleanup of components during uninstall

#63 Missing cleanup of components during uninstall

---

test/e2e/cli/cli_no-setup_test.go

fix upgrade tests

---

smallsetup/SetupNetworking.ps1
smallsetup/StartK8s.ps1
smallsetup/StopK8s.ps1
smallsetup/baseimage/BaseImage.module.psm1
smallsetup/common/GlobalFunctions.ps1
smallsetup/common/vmtools/InstallWindowsVM.ps1
smallsetup/windowsnode/InstallContainerd.ps1
smallsetup/windowsnode/InstallFlannel.ps1

#63 corrected user messages

---

lib/modules/k2s/k2s.node.module/linuxnode/distros/scripts/install_go.sh
smallsetup/common/BuildImage.ps1
smallsetup/linuxnode/scripts/install_go.sh

* Supports building with $env:GOVERSION
* Added support for building with multiple go versions.

#205 feat(buildimage): Added support for GOVERSION

---

smallsetup/common/BuildImage.ps1

Remove carriage line endings in shell script

#205 fix(buildimage): Remove carriage line endings in shell script

---

addons/smb-share/Disable.ps1
addons/smb-share/Enable.ps1
addons/smb-share/hooks/Setup-SmbShare.AfterUninstall.ps1
addons/smb-share/module/Smb-share.module.psm1
addons/smb-share/module/Smb-share.module.unit.tests.ps1

#99 fix(smb-share addon): error result separated from stdout

---

pkg/k2s/cmd/system/package/package.go
pkg/k2s/cmd/system/package/package_test.go
pkg/k2s/cmd/system/reset/network.go
pkg/k2s/cmd/system/reset/reset.go
pkg/k2s/cmd/system/system.go
smallsetup/helpers/BuildK2sZipPackage.ps1

system package command for creating package

56 system package command for creating package

---

lib/modules/k2s/k2s.node.module/linuxnode/distros/scripts/install_go.sh
smallsetup/common/BuildImage.ps1
smallsetup/linuxnode/scripts/install_go.sh

#205 chore(buildimage) Switch to go1.21.4 as default

---

lib/scripts/k2s/image/Build-Image.ps1

#205 chore(buildimage): update modules script

---

lib/scripts/k2s/image/Export-Image.ps1
pkg/k2s/cmd/image/export.go
smallsetup/helpers/ExportImage.ps1
smallsetup/helpers/ImportImage.ps1

pull all platform layers before exporting windows image

pull all platform layers before exporting windows image

---

lib/scripts/k2s/image/Build-Image.ps1
smallsetup/common/BuildImage.ps1

#205 fixes (buildimage): minor refactoring

---

test/e2e/cli/cmd/system/nosetup/system_no-setup_test.go
test/e2e/cli/cmd/system/setuprequired/system_setup-required_test.go

Adding e2e tests for system package cmd

Adding e2e tests for system package cmd

---

test/execute_all_tests.ps1

Possiblity to exclude Powershell or Go tests

Possiblity to exclude Powershell or Go tests

---

.gitignore
build/bom/k2s-bom.xml

updated gitignore and added license

#128 chore(sbom): updated gitignore and added license

---

test/e2e/cli/cmd/system/nosetup/system_no-setup_test.go

disable system package test in CI

disable system package test in CI

---

lib/modules/k2s/k2s.node.module/windowsnode/network/network.module.psm1
smallsetup/common/GlobalFunctions.ps1

One fix for server 2019 besides many other improvements in the test workflow.

In case of server 2019 they return errors

---

test/e2e/cli/cmd/system/nosetup/system_no-setup_test.go

Enable system package e2e test again

Enable system package e2e test again

---

addons/gateway-nginx/README.md

add docu for gateway-nginx addon

add docu for gateway-nginx addon

---

addons/gpu-node/README.md

add docu for gpu-node addon

---

README.md
addons/README.md

Improved documentation whith quickstart

---

README.md

239 quick start

---

addons/dashboard/README.md
addons/exthttpaccess/README.md
addons/gateway-nginx/README.md
addons/gpu-node/README.md
addons/ingress-nginx/README.md
addons/kubevirt/BuildKubevirtImage.ps1
addons/kubevirt/README.md
addons/metrics-server/README.md
addons/monitoring/README.md
addons/monitoring/manifests/plutono/deployment.yaml
addons/monitoring/manifests/vali/statefulset.yaml
addons/monitoring/manifests/valitail/daemonset.yaml
addons/monitoring/setup.md
addons/registry/README.md
addons/smb-share/README.md
addons/traefik/README.md

Add docu for addons

---

addons/exthttpaccess/README.md
addons/kubevirt/README.md
addons/monitoring/README.md
addons/registry/README.md

Improve addons docu

---

smallsetup/upgrade/Start-ClusterUpgrade.ps1

No upgrade for non K2s clusters

No upgrade from non K2s clusters

---

lib/modules/k2s/k2s.infra.module/yaml/yaml.module.psm1
pkg/base/cli/cli.go
pkg/base/logging/logging.go
pkg/network/devgon/cmd/cmd.go
pkg/util/yaml2json/main.go
pkg/util/yaml2json/main_test.go

#5 feat!(yaml2json): slog boilerplate moved to shared package

---

pkg/k2s/utils/logging/logging.go
pkg/network/devgon/main.go
pkg/util/yaml2json/main.go

#5fix!([CLI], devgon, yaml2json): slog writing to stdout instead of stderr

---

pkg/k2s/cmd/image/resetwinstorage.go
test/e2e/cli/cmd/image/nosetup/image_no-setup_test.go

#31 fix([CLI] image reset-win-storage)!: warning instead of error when not installed

---

k2s/go.sum.license

#18 chore(license): missing license file added

---

.github/workflows/build-k2s-cli.yml

#18 build([CLI]): trigger path adapted

---

k2s/cmd/k2s/cmd/install/install.go
k2s/cmd/k2s/cmd/start/start.go
k2s/cmd/k2s/cmd/stop/stop.go
k2s/cmd/k2s/cmd/uninstall/uninstall.go
k2s/cmd/k2s/config/config.go
k2s/cmd/k2s/config/config_test.go
k2s/cmd/k2s/config/defs/defs.go

#18 refactor([CLI] config): obsolete code removed; script path usage consolidated

---

k2s/cmd/k2s/addons/status/print.go
k2s/cmd/k2s/cmd/addons/cmd/list/list.go
k2s/cmd/k2s/cmd/common/common.go
k2s/cmd/k2s/cmd/image/list.go
k2s/cmd/k2s/cmd/status/status.go

#18 fix([CLI]): loading indicator glitches removed

---

k2s/cmd/k2s/cmd/cmd.go
k2s/internal/config/config.go
k2s/internal/config/config_test.go
k2s/internal/setupinfo/setupinfo.go
k2s/test/e2e/addons/export_import_test.go
k2s/test/e2e/addons/smb-share/smb_share_test.go
k2s/test/e2e/cli/cmd/image/setuprequired/systemrunning/image_system-running_test.go
k2s/test/e2e/cli/cmd/status/setuprequired/systemrunning/status_system-running_test.go
k2s/test/e2e/cli/cmd/status/setuprequired/systemstopped/status_system-stopped_test.go
k2s/test/e2e/cli/cmd/system/setuprequired/systemstopped/system_system-stopped_test.go
k2s/test/e2e/cluster/core/core_test.go
k2s/test/framework/README.md
k2s/test/framework/k2s/kubeproxy.go
k2s/test/framework/k2s/setup.go
k2s/test/framework/suite.go

#18 refactor([CLI], e2e): setupinfo consolidated

---

lib/scripts/k2s/image/registry/Switch-Registry.ps1
smallsetup/helpers/SwitchRegistry.ps1

switch registry command send to cli message fix

switch registry command send to cli message fix

---

build/bom/GenerateBom.ps1

Replaced cdxgen with trivy 0.50.0

feat (#295) Replaced cdxgen with trivy 0.50.0

---

build/bom/GenerateBom.ps1

#295 feat (sbom): adapted golang according to new structure

#295 feat (sbom): adapted golang according to new structure

---

build/bom/GenerateBom.ps1

#295 feat(sbom): trivy for container image

#295 feat(sbom): trivy for container image

---

addons/dashboard/Common.ps1
addons/dashboard/Enable.ps1
addons/monitoring/Enable.ps1

fix dashboard and monitoring addon in linux only setup

fix dashboard and monitoring addon in linux only setup

---

addons/registry/Enable.ps1
addons/registry/addon.manifest.yaml

fix registry addon for offline mode

fix registry addon for offline mode

---

addons/logging/Enable.ps1

fix logging addon for linux only setup

fix logging addon for linux only setup

---

doc/k2scli/install-uninstall_cmd.md

fix docu for enabling missing Windows features

fix docu for enabling missing Windows features

---

.gitignore

chore(sbom): update gitignore for trivy

chore(sbom): update gitignore for trivy

---

build/bom/merge/k2s-static.json

* added properties
* corrected PURL

chore(sbom): corrected purl

---

cfg/config.json
k2s/cmd/k2s/cmd/cmd.go
k2s/internal/config/config.go
k2s/internal/config/config_test.go
k2s/internal/json/json.go
k2s/internal/setupinfo/setupinfo.go
k2s/internal/setupinfo/setupinfo_test.go

#319 feat(config/setup config): display more helpful error message on loading error

---

addons/smb-share/Disable.ps1
addons/smb-share/Enable.ps1
addons/smb-share/module/Smb-share.module.psm1
smallsetup/ps-modules/log/log.module.psm1

#321 fix(smb-share addon): verbose log output restored; logging of temp password removed

---

k2s/cmd/k2s/cmd/system/ssh/common.go
k2s/cmd/k2s/cmd/system/ssh/master_test.go
k2s/cmd/k2s/cmd/system/ssh/worker_test.go
k2s/test/e2e/cli/cmd/system/setuprequired/systemstopped/system_system-stopped_test.go

Show warning when k2s system ssh and cluster is not running

Show warning when k2s system ssh and cluster is not running

---

doc/operatormanual/SecureHostAccess.md

[SecureHostAccess.md](doc/operatormanual/SecureHostAccess.md) was documenting only a simple scenario for NGINX, and a more complex one for IIS.
Now the NGINX example covers the same scenario as the one for IIS: both show how two different paths of external requests are forwarded to different local private URLs.
n.a.

secure host access - doc update

---

addons/Get-EnabledAddons.ps1
addons/addons.module.psm1

use new logging module, fix CI pipeline

use new logging module, fix CI pipeline

---

lib/modules/k2s/k2s.infra.module/log/log.module.psm1
lib/scripts/k2s/base/Invoke-ExecScript.ps1
smallsetup/helpers/sshm.ps1
smallsetup/helpers/sshw.ps1
smallsetup/ps-modules/log/log.module.psm1

fix log handling for ssh and stdout

fix log handling for ssh and stdout

---

README.md
doc/K8s_OfflinePackages.md
k2s/cmd/k2s/cmd/system/package/package.go
k2s/cmd/k2s/cmd/system/package/package_test.go
k2s/test/e2e/cli/cmd/system/nosetup/system_no-setup_test.go
smallsetup/helpers/BuildK2sZipPackage.ps1

Add docu for package creation and improve handling

Add docu for package creation and improve handling

---

k2s/cmd/k2s/cmd/system/package/package.go

add complete message to system package command

add complete message to system package command

---

addons/dashboard/Get-Status.ps1
addons/traefik/Get-Status.ps1
k2s/test/e2e/addons/dashboard/dashboard_test.go
k2s/test/e2e/addons/traefik/traefik_test.go
k2s/test/e2e/cli/cmd/addons/setuprequired/systemrunning/addons_system-running_test.go
k2s/test/e2e/cli/cmd/status/setuprequired/systemrunning/status_system-running_test.go
k2s/test/e2e/cli/cmd/status/setuprequired/systemstopped/status_system-stopped_test.go
k2s/test/framework/regex/regex.go

#346 test([e2e] dashboard/traefik addons): status cmd tests added

---

addons/gpu-node/manifests/nvidia-device-plugin.yaml

use official nvidia device plugin image with WSL support

use official nvidia device plugin image with WSL support

---

addons/exthttpaccess/Disable.ps1
addons/exthttpaccess/Enable.ps1
addons/exthttpaccess/Get-Status.ps1
addons/exthttpaccess/common.module.psm1
addons/exthttpaccess/hooks/Remove-ExtHttpAccess.AfterUninstall.ps1
k2s/test/e2e/addons/exthttpaccess/exthttpsaccess_test.go
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/nssm/nssm.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1

346-addons

---

.github/workflows/build-k2s-cli.yml
k2s/go.mod
k2s/go.sum

#346 build([CLI]): test folder excluded from action trigger /  #346 deps(k2s): go mod tidy

---

addons/gpu-node/README.md
k2s/test/e2e/addons/gpu-node/gpu-node_test.go
k2s/test/e2e/addons/gpu-node/workloads/cuda-sample.yaml
k2s/test/e2e/addons/gpu-node/workloads/kustomization.yaml
k2s/test/e2e/addons/gpu-node/workloads/namespace.yaml
k2s/test/framework/k8s/k8s.go

#346 test([e2e] gpu-node addon): acceptance test added (exluded from CI/CD)

---

addons/gpu-node/Disable.ps1
addons/gpu-node/Enable.ps1
addons/gpu-node/Get-Status.ps1
k2s/test/e2e/addons/gpu-node/gpu-node_test.go

#346 refactor(gpu-node addon): globals removed

---

lib/scripts/k2s/install/Install.ps1
smallsetup/InstallK8s.ps1

fix --skip-start after installation

fix --skip-start after installation

---

addons/dashboard/Enable.ps1
addons/dashboard/common.module.psm1
addons/gateway-nginx/Enable.ps1
addons/gateway-nginx/gateway-nginx.module.psm1

346-refactor

---

smallsetup/InstallK8s.ps1

Uses already available installation path value instead of global variable.

#348 refactor(install): Uses already available installation path value

---

addons/monitoring/Disable.ps1
addons/monitoring/Enable.ps1
addons/monitoring/Get-Status.ps1
addons/monitoring/monitoring.module.psm1
k2s/test/e2e/addons/monitoring/monitoring_test.go
k2s/test/e2e/addons/traefik/traefik_test.go

#346 refactor(monitoring addon): globals removed; e2e test for addon status added

---

addons/registry/Disable.ps1
addons/registry/Enable.ps1
addons/registry/Get-Status.ps1
addons/registry/registry.module.psm1
k2s/test/e2e/addons/registry/registry_test.go
lib/modules/k2s/k2s.cluster.module/image/registry/registry.module.psm1
lib/modules/k2s/k2s.infra.module/config/config.module.psm1

#346 refactor(registry addon): globals removed; e2e test for addon status added

---

addons/dashboard/common.module.psm1
addons/logging/logging.module.psm1
addons/monitoring/monitoring.module.psm1
addons/registry/Get-Status.ps1
addons/registry/registry.module.psm1

#346 fix(registry addon): 'curl' alias replaced with explicit Invoke-Webrequest call

---

addons/security/addon.manifest.yaml
addons/security/manifests/cert-manager.yaml

#346 fix(security addon): duplicate additional images definition removed from manifest; cert mngr source link added

---

build/bom/merge/k2s-static.json

#295 feat(sbom): update tool name to trivy

---

build/bom/GenerateBom.ps1

added enrich feature for trivy created sboms

#295 feat(sbom): added enrich feature

---

smallsetup/InstallK8s.ps1

The prerequisites checks contained in existing modules are now being used.

#348 refactor(install): Uses the prerequisites checks from existing modules

---

bin/README.md
doc/k2scli/install-uninstall_cmd.md
lib/modules/k2s/k2s.node.module/linuxnode/baseimage/base-image.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/setuplinuxnode.module.psm1
lib/modules/k2s/k2s.node.module/vmnode/vmnode.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/containerd/containerd.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/flannel/flannel.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1
lib/scripts/k2s/install/Install.ps1
lib/scripts/k2s/start/Start.ps1
lib/scripts/k2s/stop/Stop.ps1
lib/scripts/k2s/uninstall/Uninstall.ps1
lib/scripts/multivm/install/Install.ps1
lib/scripts/multivm/uninstall/Uninstall.ps1
smallsetup/InstallK8s.ps1
smallsetup/StartK8s.ps1
smallsetup/UninstallK8s.ps1
smallsetup/common/BuildImage.ps1
smallsetup/common/vmtools/InstallWindowsVM.ps1
smallsetup/kubemaster/InstallKubeMaster.ps1
smallsetup/kubemaster/UninstallKubeMaster.ps1
smallsetup/multivm/Install_MultiVMK8sSetup.ps1
smallsetup/multivm/Uninstall_MultiVMK8sSetup.ps1

remove small k8s findings

---

addons/dashboard/common.module.psm1
addons/logging/logging.module.psm1
addons/monitoring/monitoring.module.psm1

Improve duco for accessing dashboard, logging and monitoring addon with ingress

Improve duco for accessing dashboard, logging and monitoring addon with ingress

---

addons/kubevirt/Disable.ps1
k2s/test/e2e/addons/kubevirt/kubevirt_test.go

346-kubevirt

---

addons/security/Disable.ps1
addons/security/Enable.ps1
addons/security/Get-Status.ps1
addons/security/security.module.psm1
k2s/test/e2e/addons/security/security_test.go

#346 feat(security addon): status added; basic e2e tests added

---

doc/contributing/CONTRIBUTING.md

#346 doc(contributing): licensing section added

---

addons/Get-EnabledAddons.ps1

#346 refactor(addons ls): globals removed

---

smallsetup/InstallK8s.ps1

Uses the grouping modules instead of the individual ones.

#348 refactor(install): Uses grouping modules

---

lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/flannel/flannel.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/windows-exporter/windows-exporter.module.psm1
smallsetup/InstallK8s.ps1
smallsetup/ps-modules/only-while-refactoring/installation/still-to-merge.isolatedcalledscripts.module.psm1

InstallK8s.ps1 uses a module to create the file 'WindowsNodeArtifacts.zip'

#348 refactor(install): Uses module to create the file 'WindowsNodeArtifacts.zip'

---

addons/kubevirt/addon.manifest.yaml
addons/security/Enable.ps1
addons/security/addon.manifest.yaml
k2s/test/e2e/addons/security/security_test.go

#346 fix(security addon): proxy param added

---

lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1
smallsetup/common/GlobalFunctions.ps1

fix addons import

---

lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/containerd/containerd.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/docker/docker.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/flannel/flannel.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/kube-tools/kube-tools.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/downloader.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1
smallsetup/InstallK8s.ps1
smallsetup/ps-modules/only-while-refactoring/installation/still-to-merge.isolatedcalledscripts.module.psm1

InstallK8s.ps1 uses a module to set up the Windows node.

#348 refactor(install): Uses a module to set up the Windows node

---

lib/modules/k2s/k2s.cluster.module/setup/setupcluster.module.psm1
smallsetup/InstallK8s.ps1
smallsetup/ps-modules/only-while-refactoring/installation/still-to-merge.isolatedcalledscripts.module.psm1

InstallK8s.ps1 uses a module to join the Windows node into the cluster.

#348 refactor(install): Uses a module to join the Windows node into the cluster

---

lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1
smallsetup/common/GlobalFunctions.ps1

check source path exists when copying to kubemaster

check source path exists when copying to kubemaster

---

lib/scripts/k2s/image/Export-Image.ps1

#346 fix(addons export): nerdctl unknown in e2e tests

---

addons/Export.ps1
k2s/test/e2e/addons/export_import_test.go

#346 fix(addons export): missing backslash added

---

lib/scripts/k2s/image/Import-Image.ps1

#346 fix(addons import): nerdctl unknown in e2e tests

---

lib/modules/k2s/k2s.cluster.module/system/system.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/network/network.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/services/services.module.psm1
smallsetup/InstallK8s.ps1
smallsetup/StartK8s.ps1

StartK8s.ps1 uses the modules instead of the scripts GlobalVariables.ps1 and GlobalFunctions.ps1

#349 refactor(start): Uses modules instead of GlobalVariables.ps1 and GlobalFunctions.ps1

---

lib/modules/k2s/k2s.cluster.module/setup/setupcluster.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/docker/docker.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1
smallsetup/UninstallK8s.ps1
smallsetup/ps-modules/only-while-refactoring/installation/still-to-merge.isolatedcalledscripts.module.psm1

UninstallK8s.ps1 uses the modules instead of the scripts GlobalVariables.ps1 and GlobalFunctions.ps1

#353 refactor(uninstall): Uses modules instead of GlobalVariables.ps1 and GlobalFunctions.ps1

---

addons/registry/Enable.ps1

registry addon: fix checking for setupinfo

registry addon: fix checking for setupinfo

---

smallsetup/StartK8s.ps1
smallsetup/StopK8s.ps1
smallsetup/UninstallK8s.ps1

Adds a flag to StopK8s.ps1 to skip the display of a header message.

#351 refactor(stop): Adds flag to skip the display of a header message

---

k2s/test/e2e/cli/cmd/addons/nosetup/corruptedstate/addons_corrupted-state_test.go
k2s/test/e2e/cli/cmd/image/nosetup/corruptedstate/image_corrupted-state_test.go
k2s/test/e2e/cli/cmd/install/nosetup/corruptedstate/install_corrupted-state_test.go
k2s/test/e2e/cli/cmd/start/nosetup/corruptedstate/start_corrupted-state_test.go
k2s/test/e2e/cli/cmd/status/nosetup/corruptedstate/status_corrupted-state_test.go
k2s/test/e2e/cli/cmd/stop/nosetup/corruptedstate/stop_corrupted-state_test.go
k2s/test/e2e/cli/cmd/system/nosetup/corruptedstate/system_corrupted-state_test.go

remove corrupted state tests from CI for now

remove corrupted state tests from CI for now

---

.github/workflows/ci-unit-tests.yml

#411 build(CI): documentation excluded from PR trigger

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/bug_report.md.license
.github/ISSUE_TEMPLATE/custom.md
.github/ISSUE_TEMPLATE/custom.md.license
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/feature_request.md.license

#411 chore(issue templates): license added as separate files

---

.github/workflows/ci-unit-tests.yml

#411 build(CI): issue templates excluded from triggers

---

doc/contributing/CONTRIBUTING.md

#411 doc(contributing): reuse tool hint for local checks added

---

README.md

#447 doc(README): CI badge for REUSE checks added

---

k2s/test/e2e/cli/cmd/image/setuprequired/systemrunning/image_system-running_test.go

#350 fix([e2e] image reset-win-storage): more typos

---

build/bom/GenerateBom.ps1

Annotation of sbom is conditional

#295 feat(sbom): annotation of sbom is conditional

---

addons/dashboard/Enable.ps1
addons/exthttpaccess/Enable.ps1
addons/gateway-nginx/Enable.ps1
addons/ingress-nginx/Enable.ps1
addons/logging/Enable.ps1
addons/monitoring/Enable.ps1
addons/registry/Enable.ps1
addons/smb-share/module/Smb-share.module.psm1
addons/traefik/Enable.ps1
k2s/cmd/k2s/cmd/addons/export/export.go
k2s/cmd/k2s/cmd/addons/importcmd/importcmd.go
k2s/cmd/k2s/cmd/common/common.go
k2s/internal/json/json.go
k2s/internal/setupinfo/setupinfo.go

#457 fix(multivm addons): erroneous commands disabled

---

addons/smb-share/module/Smb-share.module.unit.tests.ps1

#457 fix(smb-share addon): unit tests

---

lib/modules/k2s/k2s.cluster.module/image/image.module.psm1

fix getting pushed container image from local registry

fix getting pushed container image from local registry

---

k2s/test/e2e/addons/export_import_test.go
k2s/test/e2e/addons/generic/build_image/build_image_test.go
lib/modules/k2s/k2s.cluster.module/image/image.module.psm1

fix image e2e tests

---

lib/scripts/k2s/image/Build-Image.ps1

fix docker.exe path in build image script

fix docker.exe path in build image script

---

build/bom/merge/k2s-static.json

Removed extra slash in PURL for crictl component

#295 feat(sbom): fix typo in PURL

---

lib/modules/k2s/k2s.node.module/windowsnode/system/system.module.psm1
lib/scripts/buildonly/install/Install.ps1
lib/scripts/multivm/install/Install.ps1
smallsetup/InstallK8s.ps1
smallsetup/common/GlobalFunctions.ps1
smallsetup/common/InstallBuildOnlySetup.ps1
smallsetup/multivm/Install_MultiVMK8sSetup.ps1

refactor(install): fix setting WSL config with correct memory and processor count

refactor(install): fix setting WSL config with correct memory and processor count

---

lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/nssm/nssm.module.psm1
lib/scripts/k2s/start/Start.ps1
smallsetup/StartK8s.ps1
smallsetup/StopK8s.ps1
smallsetup/common/GlobalFunctions.ps1

k2s start: fix "failed to start service flanneld"

k2s start: fix "failed to start service flanneld"

---

lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/containerd/containerd.module.psm1
lib/scripts/k2s/image/Clean-Images.ps1
smallsetup/linuxnode/linuxnode.module.psm1
smallsetup/linuxnode/linuxnode.module.unit.tests.ps1
smallsetup/windowsnode/InstallContainerd.ps1

increase timeout for crictl -> crio

increase timeout for crictl -> crio, containerd

---

lib/modules/k2s/k2s.node.module/linuxnode/baseimage/base-image.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/baseimage/provisioning.module.psm1
smallsetup/baseimage/BaseImage.module.psm1

The timeout for the VM to get stopped was increased to 6 minutes.

#348 refactor(install): Increases the waiting time in seconds for the VM to get stopped.

---

lib/scripts/k2s/upgrade/upgrade.module.psm1
lib/scripts/k2s/upgrade/upgrade.module.unit.tests.ps1

#439 fix(upgrade): minor and patch version update rules implemented

---

build/bom/GenerateBom.ps1

#295 Minor changes for bom script generation

---

k2s/test/e2e/addons/generic/build_image/build_image_test.go
k2s/test/framework/k2s/image.go

adding tests for image pull, push and tag

adding tests for image pull, push and tag

---

k2s/test/e2e/cli/cmd/image/nosetup/corruptedstate/image_corrupted-state_test.go
k2s/test/e2e/cli/cmd/image/nosetup/image_no-setup_test.go
k2s/test/e2e/cli/cmd/image/setuprequired/systemstopped/image_system-stopped_test.go
lib/scripts/k2s/image/Build-Image.ps1
lib/scripts/k2s/image/Export-Image.ps1
lib/scripts/k2s/image/Import-Image.ps1
lib/scripts/k2s/image/Remove-Image.ps1
lib/scripts/k2s/image/registry/Add-Registry.ps1
lib/scripts/k2s/image/registry/Switch-Registry.ps1

#246 fix image unit tests

---

k2s/cmd/k2s/cmd/system/upgrade/upgrade.go

#497 fix([CLI] system upgrade): CMD help updated

---

lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1
smallsetup/StartK8s.ps1

added external switch check for start with minor improvements

#250 feat(start): added external switch check for start

---

k2s/cmd/k2s/cmd/image/build.go

added info about pushing container images and registry options

#87 feat(doc): added info about pushing container images

---

lib/scripts/k2s/system/package/New-K2sPackage.ps1
smallsetup/baseimage/BuildAndProvisionKubemasterBaseImage.ps1
smallsetup/baseimage/BuildAndProvisionKubeworkerBaseImage.ps1
smallsetup/baseimage/provisioning.module.psm1
smallsetup/common/GlobalFunctions.ps1
smallsetup/kubemaster/InstallKubeMaster.ps1
smallsetup/multivm/Uninstall_MultiVMK8sSetup.ps1

fix multi-vm and linux-only setup

fix multi-vm and linux-only setup

---

lib/modules/k2s/k2s.node.module/windowsnode/network/network.module.psm1
lib/scripts/k2s/start/Start.ps1
smallsetup/StartK8s.ps1

Implemented a restart of Network Location Awareness service to eliminate issues with cbr0 switch creation.

Implemented NlaSvc restart

---

addons/logging/manifests/fluentbit/windows/configmap-windows.yaml

fix logging parser

---

smallsetup/ps-modules/windows-support/windows-support.module.psm1

Fix typo in Windows Tag Suffix

---

README.md
docs/dev-guide/architecture.md
docs/dev-guide/contributing/index.md
docs/quickstart/index.md
mkdocs.yml

#234 docs(site): quick start migrated; README and docs consolidated

---

docs/dev-guide/contributing/building-locally.md
docs/dev-guide/contributing/index.md
docs/dev-guide/contributing/licensing.md
docs/dev-guide/contributing/submitting-changes.md
docs/dev-guide/contributing/updating-documentation.md
mkdocs.yml

#234 docs(site): docs creation added; contributing section re-structured

---

mkdocs.yml

#234 chore(docs): copyright footer updated

---

lib/modules/k2s/k2s.cluster.module/image/image.module.psm1

prep for win multi-platform build

#87 prep for win multi-platform build

---

docs/overrides/main.html
mkdocs.yml

#234 docs(site): versioning activated

---

docs/overrides/main.html

#234 docs(site): latest hint made clearer

---

.github/workflows/build-docs-next.yml
.vscode/spellright.dict
README.md
docs/dev-guide/contributing/updating-documentation.md
docs/index.md

#234 docs(site)/build(site): workflow updated to build always next version; updating guide updated

---

.github/workflows/build-docs-next.yml

#234 fix(build-docs-next): local repo instance needed

---

docs/dev-guide/contributing/updating-documentation.md

#234 fix(docs): typo in workflow link

---

lib/scripts/k2s/image/Build-Image.ps1

Removed uninitialized variable which was used as a condition

#87 minor fix in build image

---

k2s/test/e2e/cli/cmd/system/setuprequired/systemrunning/system_system-running_test.go
lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1

#498 fix(vm.module.psm1): errors on copy from/to control-plane get detected

---

lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1

#498 fix(vm.module.psm1): stopped ignoring IgnoreErrors param

---

lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1

#554 fix(vm.module.psm1): $error check replaces by $LASTEXITCODE check; logging improved

---

lib/scripts/k2s/image/Build-Image.ps1

Improve error message when build push fails.

#87 fix(buildimage): improve push error message

---

addons/dashboard/README.md
addons/dashboard/common.module.psm1
addons/dashboard/manifests/dashboard-nginx-ingress.yaml
addons/dashboard/manifests/dashboard-traefik-ingress.yaml
addons/ingress-nginx/README.md
addons/ingress-nginx/manifests/cluster-net-ingress.yaml
addons/logging/README.md
addons/logging/logging.module.psm1
addons/logging/manifests/opensearch-dashboards/ingress.yaml
addons/logging/manifests/opensearch-dashboards/traefik.yaml
addons/monitoring/README.md
addons/monitoring/manifests/plutono/configmap.yaml
addons/monitoring/manifests/plutono/ingress.yaml
addons/monitoring/manifests/plutono/traefik.yaml
addons/monitoring/monitoring.module.psm1
addons/security/manifests/keycloak/keycloak.yaml
addons/security/manifests/keycloak/nginx-ingress.yaml
addons/security/manifests/keycloak/oauth2-proxy.yaml
addons/security/manifests/keycloak/traefik-ingress.yaml
addons/security/security.module.psm1
addons/traefik/README.md
addons/traefik/manifests/cluster-net-ingress.yaml
k2s/test/e2e/addons/dashboard/dashboard_test.go
k2s/test/e2e/addons/ingress-nginx/ingress-nginx_test.go
k2s/test/e2e/addons/logging/logging_test.go
k2s/test/e2e/addons/monitoring/monitoring_test.go
k2s/test/e2e/addons/traefik/traefik_test.go
lib/modules/k2s/k2s.cluster.module/setup/setupcluster.module.psm1
smallsetup/AddToHosts.ps1
smallsetup/multivm/Install_MultiVMK8sSetup.ps1

258 security addon

---

addons/logging/Enable.ps1

increase timeout for readiness check of logging components

increase timeout for readiness check of logging components

---

lib/modules/k2s/k2s.cluster.module/system/system.module.psm1
lib/scripts/k2s/start/Start.ps1
smallsetup/StartK8s.ps1

Implemented a restart mechanism for Kubemaster when cni0 is not initialized with the correct IP address. Kubemaster shall be restarted atmost 3 times when this issue happens.

#511 Restart kubemaster when cni0 not initialized correctly

---

lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
smallsetup/linuxnode/linuxnode.module.psm1
smallsetup/linuxnode/linuxnode.module.unit.tests.ps1

Added default host entry in coredns

#258 feat(coredns): added host entry

---

.github/workflows/build-k2s-cli.yml
.github/workflows/release.yml

ci: exclude ci types and correct remotes

---

.github/workflows/build-k2s-cli.yml
.github/workflows/release.yml

Ci workflows

---

.github/workflows/build-k2s-artifacts.yml
.github/workflows/build-k2s-cli.yml
.github/workflows/release.yml

ci: change all artifacts workflow to use ssh agent

ci: workflows

---

build/bom/GenerateBom.ps1

Generating SBOM with specific addons
Example: `.\build\bom\GenerateBom.ps1 -Annotate -Addons registry,traefik`

chore(sbom): generate sbom accepts addons list

---

addons/addons.module.psm1
addons/addons.module.unit.tests.ps1

fix(addons): copy required hooks for upgrade

---

lib/modules/k2s/k2s.node.module/linuxnode/setup/control-plane-node.module.psm1
lib/scripts/k2s/start/Start.ps1

fix: increase timout for slow machines #595

fix: increase timout for slow machines #595

---

k2s/cmd/k2s/cmd/common/common.go
k2s/cmd/k2s/cmd/system/upgrade/upgrade.go
lib/scripts/k2s/system/upgrade/Start-ClusterUpgrade.ps1

Fixes #590 
k2s cli will now indicate error when there are errors during upgrade.

fix(upgrade): error handling improvements

---

lib/modules/k2s/k2s.node.module/linuxnode/baseimage/provisioning.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/control-plane-node.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/windows-worker-node.module.psm1
smallsetup/InstallK8s.ps1
smallsetup/UninstallK8s.ps1
smallsetup/baseimage/provisioning.module.psm1

#348 #349 #351 #353
Fixes high level log messages

#348,#349,#351,#353 refactor(install, start, stop, uninstall): Fixes high level log messages

---

k2s/cmd/k2s/cmd/system/upgrade/upgrade.go
k2s/cmd/k2s/cmd/system/upgrade/upgrade_test.go
lib/modules/k2s/k2s.cluster.module/upgrade/upgrade.module.psm1
lib/modules/k2s/k2s.infra.module/hooks/hooks.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1
lib/scripts/k2s/system/upgrade/Start-ClusterUpgrade.ps1

feat(upgrade): add cluster upgrade hook

feat(upgrade): add cluster upgrade hook

---

lib/modules/k2s/k2s.node.module/windowsnode/downloader/downloader.module.psm1

Refs: #601 
Fix for missing import of pause image during installation.

fix(offline): import pause image during installation

---

cfg/config.json

refactor(setup-config)!: setup.json moved to programdata dir #24

---

lib/modules/k2s/k2s.infra.module/config/config.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1
lib/scripts/multivm/uninstall/Uninstall.ps1
smallsetup/common/UninstallBuildOnlySetup.ps1
smallsetup/multivm/Uninstall_MultiVMK8sSetup.ps1

refactor(setup-config)!: delete whole config dir on uninstall #24

---

k2s/test/e2e/cli/cmd/image/nosetup/image_no-setup_test.go

Corrected no setup test to not include entry for reset-win-storage command.

ci: fixed k2s cli build

---

k2s/test/e2e/cli/cmd/image/nosetup/corruptedstate/image_corrupted-state_test.go
k2s/test/e2e/cli/cmd/image/nosetup/image_no-setup_test.go

fixed no-setup and corruptedstate tests for reset-win-storage command on release branch

fix: fixed no-setup and corruptedstate tests for reset-win-storage command on release branch

---

k2s/cmd/k2s/cmd/system/upgrade/upgrade.go
k2s/cmd/k2s/cmd/system/upgrade/upgrade_test.go
lib/modules/k2s/k2s.cluster.module/upgrade/upgrade.module.psm1
lib/scripts/k2s/system/upgrade/Start-ClusterUpgrade.ps1

feat(upgrade): specify backup directory

feat(upgrade): specify backup directory

---

k2s/test/e2e/cluster/core/core_test.go
k2s/test/framework/env.go
k2s/test/framework/suite.go
test/execute_all_tests.ps1

Offline system test execution when Internet is not available

feat(e2e): offline system test mode

---

k2s/test/e2e/cluster/core/core_test.go
k2s/test/framework/env.go
k2s/test/framework/suite.go
test/execute_all_tests.ps1

offline system test, merging from main

feat(e2e): system test offline merged from main

---

lib/modules/k2s/k2s.infra.module/log/log.module.psm1

Added error markers for user message.

feat(log): added error markers for console message

---

lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/system/system.module.psm1
lib/scripts/buildonly/install/Install.ps1
lib/scripts/k2s/base/Invoke-ExecScript.ps1
smallsetup/common/InstallBuildOnlySetup.ps1

Added markers for install pre-requisites. These markers are meant only for error handling in the CLI.

feat(install): added install pre-requisites markers

---

k2s/cmd/k2s/cmd/install/core/installer.go

feat(install): updated user message for pre-requisite failure

---

docs/dev-guide/contributing/powershell-dev.md

doc changes for PowerShell markers

feat(docs): added info about PowerShell markers

---

k2s/cmd/k2s/cmd/system/users/add.go
k2s/internal/host/host.go
k2s/internal/host/host_test.go
k2s/internal/nodes/nodes.go
k2s/internal/ssh/keygen.go
k2s/internal/ssh/ssh_test.go
k2s/internal/users/common.go
k2s/internal/users/k8s_access.go
k2s/internal/users/ssh_access.go
k2s/internal/users/users.go

feat(system-users): control-plane gets added to known_hosts file #24

---

lib/modules/k2s/k2s.infra.module/config/config.module.psm1
smallsetup/common/GlobalVariables.ps1

refactor(images): kubernetes_images.json moved to ProgramData #24

---

k2s/cmd/k2s/cmd/system/ssh/common.go

fix(ssh): Escape system ssh m properly

fix(ssh): Escape system ssh m properly

---

k2s/internal/addons/addons.go
k2s/internal/addons/addons_test.go
k2s/test/e2e/cli/cmd/addons/nosetup/addons_no-setup_test.go
k2s/test/e2e/cli/cmd/addons/setuprequired/systemstopped/addons_system-stopped_test.go

fix(addons): fix cli addons tests

fix(addons): fix cli addons tests

---

k2s/test/e2e/cli/cmd/addons/setuprequired/systemstopped/addons_system-stopped_test.go

fix(addons): fix addons_system-stopped_test

fix(addons): fix addons_system-stopped_test

---

k2s/test/e2e/cli/cmd/addons/nosetup/corruptedstate/addons_corrupted-state_test.go

fix(addons): fix addons_corrupted-state_test

fix(addons): fix addons_corrupted-state_test

---

addons/ingress/nginx/README.md
addons/ingress/traefik/README.md

doc(README): update ingress addon routes

docs(README): update ingress addon routes

---

addons/ingress/nginx/README.md
addons/ingress/traefik/README.md

docs(addons): fix docs of ingress nginx and traefik

docs(addons): fix docs of ingress nginx and traefik

---

lib/modules/k2s/k2s.cluster.module/setup/setupcluster.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/containerd/containerd.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/dnsproxy/dnsproxy.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/downloader.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/network/network.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/windows-worker-node.module.psm1
smallsetup/InstallK8s.ps1
smallsetup/StartK8s.ps1
smallsetup/StopK8s.ps1

Renamed parameter 'WorkerNodeNumber' to 'PodSubnetworkNumber'

refactor(install): parameter renaming

---

k2s/test/e2e/addons/generic/build_image/build_image_test.go

fix(addons): build_image_test

---

docs/op-manual/adding-k2s-users.md
k2s/internal/users/users.go

feat(system-users): Win system account can be granted access #24

---

build/bom/DumpK2sImages.ps1

fix(images): migrate DumpK2sImages.ps1 to new addon structure

fix(images): migrate DumpK2sImages.ps1 to new addon structure

---

k2s/cmd/k2s/cmd/system/ssh/common.go
k2s/cmd/k2s/utils/utilities.go
lib/scripts/k2s/system/ssh/sshm.ps1

fix(ssh): Escape '$'

---

docs/troubleshooting/diagnostics.md

added diagnostic info for networking issues

feat(docs): added diagnostic info for networking issues

---

addons/README.md
addons/Update-Readme.ps1

docs(addons): fix addon docu and Update-Readme.ps1

docs(addons): fix addon docu 

---

k2s/cmd/k2s/cmd/system/dump/dump.go
lib/modules/k2s/k2s.infra.module/dump/dump.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1
lib/scripts/k2s/system/dump/network_dump.ps1

- Added NetConnectionProfile dump
- `k2s system dump` will work without k2s installed. [Diagnostic purpose]

feat(system): network dump improvements

---

k2s/test/e2e/addons/dashboard/dashboard_test.go
k2s/test/e2e/addons/logging/logging_test.go
k2s/test/e2e/addons/monitoring/monitoring_test.go
k2s/test/e2e/addons/security/security_test.go
k2s/test/framework/k8s/kubectl.go

fix(tests): kubectl now in bin/kube

fix(tests): kubectl now in bin/kube

---

docs/op-manual/creating-offline-package.md
docs/op-manual/secure-host-access.md

docs(package): minor fixes

---

addons/security/addons/dashboard-nginx-ingress-security.yaml

fix(security): use new dashboard namespace

fix(security): use new dashboard namespace

---

addons/security/README.md

fix(docs): updated addon name in security

---

lib/scripts/k2s/system/upgrade/Start-ClusterUpgrade.ps1

[fix(upgrade): use correct kube tools folder](https://github.com/Siemens-Healthineers/K2s/commit/337e520e9ead7b3f1321837fa69e8801fc0ba344)

fix(upgrade): use correct kube tools folder

---

lib/modules/k2s/k2s.cluster.module/upgrade/upgrade.module.psm1
lib/scripts/k2s/system/upgrade/Start-ClusterUpgrade.ps1

fix(upgrade): resolve conflict with addons module

fix(upgrade): resolve conflict with addons module

---

lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1

Dump errors when ssh connection is not possible.

feat(ssh): dump errors in ssh connection

---

addons/rollout/README.md
addons/rollout/rollout.module.psm1

docs(rollout): fix dashboard url

docs(rollout): fix dashboard url

---

addons/gpu-node/Enable.ps1
addons/logging/Enable.ps1
addons/logging/README.md
addons/logging/logging.module.psm1
addons/logging/manifests/opensearch-dashboards/ingress-nginx.yaml
addons/logging/manifests/opensearch-dashboards/ingress-traefik.yaml
addons/logging/manifests/opensearch-dashboards/kustomization.yaml
addons/monitoring/Enable.ps1
addons/monitoring/README.md
addons/monitoring/manifests/plutono/ingress-nginx.yaml
addons/monitoring/manifests/plutono/ingress-traefik.yaml
addons/monitoring/manifests/plutono/kustomization.yaml
addons/monitoring/monitoring.module.psm1
addons/rollout/README.md
addons/rollout/manifests/argocd/base/rollout-nginx-ingress.yaml
addons/rollout/manifests/argocd/base/rollout-traefik-ingress.yaml
addons/rollout/rollout.module.psm1
addons/security/addons/logging-nginx-ingress-security.yaml
addons/security/addons/monitoring-nginx-ingress-security.yaml
addons/security/addons/rollout-nginx-ingress-security.yaml
addons/security/security.module.psm1
k2s/test/e2e/addons/logging/logging_test.go
k2s/test/e2e/addons/monitoring/monitoring_test.go
k2s/test/e2e/addons/rollout/rollout_test.go

fix(addons): security ingresses, order of enabling

fix(addons): security ingresses, order of enabling

---

lib/scripts/k2s/system/scp/scpm.ps1
lib/scripts/k2s/system/ssh/sshm.ps1

fix(ssh): improve performance

---

.github/workflows/build-vfprules-cli.yml
bin/cni/vfprules.dll.license
k2s/cmd/vfprules/vfprules/vfprules.vcxproj.license

feat(vfp): Fixes for license checks

feat(vfp): 677 starting with an pipeline

---

addons/rollout/manifests/argocd/base/argocd.yaml

adjust imagePullPolicy from Always to IfNotPresent

fix(rollout): adjust imagePullPolicy

---

addons/README.md

docs(addons): update README

---

docs/op-manual/installing-k2s.md
lib/modules/k2s/k2s.node.module/linuxnode/setup/control-plane-node.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/system/system.module.psm1

fix(ssh): check ssh version in prerequisites

fix(ssh): warning if ssh version < 8

---

k2s/internal/core/users/fs/fs.go
k2s/internal/core/users/k8s/k8s.go
k2s/internal/core/users/k8s/k8s_test.go

refactor(system-users): missing tests added #672

---

k2s/cmd/k2s/cmd/system/users/add.go
k2s/test/e2e/cli/cmd/system/setuprequired/systemrunning/users/users_systemrunning_test.go

refactor(system-users): add cmd #672

---

addons/Import.ps1
lib/modules/k2s/k2s.node.module/vmnode/vmnode.module.psm1

feat(stability): #744 test findings

---

k2s/test/e2e/cli/cmd/system/nosetup/system_no-setup_test.go
k2s/test/framework/k2s/setup.go
k2s/test/framework/suite.go
lib/scripts/k2s/system/package/New-K2sPackage.ps1

fix(system-package): removal of setup.json after package creation #745

---

lib/modules/k2s/k2s.cluster.module/image/image.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/proxy/proxy.module.psm1
lib/scripts/buildonly/install/Install.ps1
lib/scripts/buildonly/uninstall/Uninstall.ps1
lib/scripts/k2s/install/Install.ps1
lib/scripts/k2s/uninstall/Uninstall.ps1
lib/scripts/multivm/install/Install.ps1
lib/scripts/multivm/uninstall/Uninstall.ps1
smallsetup/InstallK8s.ps1
smallsetup/UninstallK8s.ps1
smallsetup/common/InstallBuildOnlySetup.ps1
smallsetup/common/UninstallBuildOnlySetup.ps1
smallsetup/multivm/Install_MultiVMK8sSetup.ps1
smallsetup/multivm/Uninstall_MultiVMK8sSetup.ps1

fix: use noproxy for registry addon in image module

---

addons/rollout/manifests/argocd/base/rollout-nginx-ingress.yaml
addons/security/addons/rollout-nginx-ingress-security.yaml
k2s/test/e2e/addons/rollout/rollout_test.go

fix(addons): use test suite proxy for rollout tests

fix(addons): use test suite proxy for rollout tests

---

lib/modules/k2s/k2s.node.module/linuxnode/baseimage/base-image.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/baseimage/provisioning.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/network/network.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/security/security.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/new-hyperv-vm-as-linuxnode.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/new-wsl-vm-as-linuxnode.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1
lib/modules/k2s/k2s.node.module/vmnode/vmnode.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/baseimage/windows-base-image.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/putty-tools/putty-tools.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/downloader.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/network/network.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/windows-worker-node.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/system/system.module.psm1

#348 #349 #351 #353
Removed not used functions from under lib/modules/k2s/k2s.node.module folder

refactor(install): clean-up of lib/modules/k2s/k2s.node.module folder

---

addons/rollout/manifests/argocd/base/rollout-nginx-ingress.yaml
addons/security/addons/rollout-nginx-ingress-security.yaml
k2s/test/e2e/addons/rollout/rollout_test.go
lib/modules/k2s/k2s.node.module/linuxnode/baseimage/base-image.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/baseimage/provisioning.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/network/network.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/security/security.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/new-hyperv-vm-as-linuxnode.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/new-wsl-vm-as-linuxnode.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1
lib/modules/k2s/k2s.node.module/vmnode/vmnode.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/baseimage/windows-base-image.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/putty-tools/putty-tools.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/downloader.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/network/network.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/windows-worker-node.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/system/system.module.psm1
test/execute_all_tests.ps1

Merge changes from Main to Debian-12 branch.

Merge Main to Debian-12 branch

---

addons/rollout/manifests/argocd/base/rollout-nginx-ingress.yaml
addons/security/addons/rollout-nginx-ingress-security.yaml
k2s/test/e2e/addons/rollout/rollout_test.go
lib/modules/k2s/k2s.node.module/linuxnode/baseimage/base-image.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/baseimage/provisioning.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/network/network.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/security/security.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/new-hyperv-vm-as-linuxnode.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/new-wsl-vm-as-linuxnode.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1
lib/modules/k2s/k2s.node.module/vmnode/vmnode.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/baseimage/windows-base-image.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/putty-tools/putty-tools.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/downloader.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/network/network.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/windows-worker-node.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/system/system.module.psm1
test/execute_all_tests.ps1

Merge changes from Main to Debian 12

Merge changes from Main to Debian 12

---

k2s/cmd/k2s/cmd/node/add/add.go
k2s/cmd/k2s/cmd/node/node.go

Draft API for node command
Refs #39

feat(node): added draft API for node command

---

k2s/cmd/k2s/cmd/node/add/add.go
k2s/cmd/k2s/cmd/node/node.go
k2s/cmd/k2s/cmd/node/remove/remove.go

feat(node): draft api for remove

---

.github/workflows/build-k2s-artifacts.yml
.github/workflows/build-k2s-cli.yml
.github/workflows/ci-unit-tests.yml
k2s/go.mod
k2s/internal/core/users/k8s/kubeconfig/kubeconfig_test.go
k2s/test/e2e/addons/generic/build_image/weather/go.mod
lib/modules/k2s/k2s.node.module/linuxnode/distros/scripts/install_go.sh
lib/scripts/k2s/image/Build-Image.ps1

chore(CLI): bump Go version to 1.23 #721

---

addons/rollout/Disable.ps1
addons/rollout/Enable.ps1
addons/rollout/addon.manifest.yaml
addons/rollout/manifests/rollout/overlay/patch.yaml
addons/rollout/rollout.module.psm1

refactor(addons): disable auth login for rollout addon

refactor(addons): disable auth login for rollout addon

---

test/execute_all_tests.ps1

chore(test): bump Pester version to 5.6.1 #721

---

.github/workflows/build-k2s-artifacts.yml
.github/workflows/build-k2s-cli.yml
.github/workflows/ci-unit-tests.yml
lib/modules/k2s/k2s.node.module/linuxnode/distros/scripts/install_go.sh
lib/scripts/k2s/image/Build-Image.ps1

chore(CLI): bump Go version to 1.23.2 #721

---

lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/docker/docker.module.psm1

Adapted uninstall based on flag

769 uninstall docker

---

lib/modules/k2s/k2s.node.module/windowsnode/setup/windows-worker-node.module.psm1

Handles variation in interface names and better error handling.

fix(loopback): handle variation in interface name

---

lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1
lib/scripts/control-plane/Install.ps1
lib/scripts/worker-node/linux/hyper-v-vm/Add.ps1

Adapts some helper functions used to perform remote calls to accept a username as parameter, thus allowing connections to hosts that have users that differ in name from the default one.

refactor(remote-connection): connections to hosts using custom username

---

lib/modules/k2s/k2s.node.module/windowsnode/proxy/proxy.module.psm1

fix(proxy): check http prefix

---

addons/Import.ps1

fix(addons): use $env:TEMP for extracting addons.zip

fix(addons): use $env:TEMP for extracting addons.zip

---

lib/modules/k2s/k2s.infra.module/config/config.module.psm1

fix(wsl): merge provide default value

---

lib/modules/k2s/k2s.infra.module/config/config.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/docker/docker.module.psm1

Show warning for existing docker service

790 wsl fix

---

addons/dashboard/manifests/ingress-nginx-secure/kustomization.yaml

fix(addons): dashboard secure ingress nginx

fix(addons): dashboard secure ingress nginx

---

addons/logging/Enable.ps1
addons/logging/manifests/logging/opensearch-dashboards/deployment.yaml
addons/logging/manifests/logging/opensearch-dashboards/rolebinding.yaml
addons/logging/manifests/logging/opensearch-dashboards/service.yaml
addons/logging/manifests/logging/opensearch-dashboards/serviceaccount.yaml
addons/logging/manifests/logging/opensearch/configmap.yaml
addons/logging/manifests/logging/opensearch/poddisruptionbudget.yaml
addons/logging/manifests/logging/opensearch/service.yaml
addons/logging/manifests/logging/opensearch/statefulset.yaml

fix(addons): fix opensearch dashboard red panel discovery

fix(addons): fix opensearch dashboard red panel discovery

---

addons/dashboard/manifests/ingress-nginx-secure/kustomization.yaml
addons/logging/Enable.ps1
addons/logging/manifests/logging/opensearch-dashboards/deployment.yaml
addons/logging/manifests/logging/opensearch-dashboards/rolebinding.yaml
addons/logging/manifests/logging/opensearch-dashboards/service.yaml
addons/logging/manifests/logging/opensearch-dashboards/serviceaccount.yaml
addons/logging/manifests/logging/opensearch/configmap.yaml
addons/logging/manifests/logging/opensearch/poddisruptionbudget.yaml
addons/logging/manifests/logging/opensearch/service.yaml
addons/logging/manifests/logging/opensearch/statefulset.yaml
addons/monitoring/manifests/monitoring/plutono/dashboards.yaml
lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/control-plane-node.module.psm1

Merge from main branch

---

addons/rollout/manifests/rollout/overlay/kustomization.yaml

fix(addons): rollout addon patch strategy

fix(addons): rollout addon patch strategy

---

lib/modules/k2s/k2s.node.module/windowsnode/setup/windows-worker-node.module.psm1

fix: only start o hns and vmcompute service

fix: fix for restart of services #819

---

addons/dashboard/README.md
addons/logging/README.md
addons/monitoring/README.md
addons/registry/README.md
lib/modules/k2s/k2s.cluster.module/image/image.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/proxy/proxy.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/system/system.module.psm1
lib/scripts/buildonly/install/Install.ps1
lib/scripts/buildonly/uninstall/Uninstall.ps1
lib/scripts/k2s/install/Install.ps1
lib/scripts/k2s/uninstall/Uninstall.ps1
lib/scripts/multivm/install/Install.ps1
lib/scripts/multivm/uninstall/Uninstall.ps1

Merging solution for #754 to 1.2

fix: image ls and no_proxy

---

lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1

#39 
Avoids piping the public key for cri-o and kubernetes into the executable 'gpg' to avoid an error related with 'device /dev/tty not present' when adding a new Debian 11 bare metal node to the cluster.
The solution consists of downloading the public key and saving it temporarily in a file. Afterwards that file is being used as input for gpg.

feat(node): fixes /dev/tty error from gpg

---

lib/scripts/worker-node/linux/bare-metal/Add.ps1

Use configured proxy while adding node

feat(node): use configured proxy

---

k2s/cmd/k2s/cmd/cmd.go
k2s/cmd/k2s/cmd/node/add/add.go

Enabling experimental node add command.

feat(node): enabling add cmd

---

k2s/internal/core/users/users_test.go
k2s/test/e2e/cli/cmd/node/setuprequired/systemrunning/copy/copy_system-running_test.go

fix(node-tests): win node tests skipped when no win worker exists

---

k2s/test/e2e/addons/generic/build_image/build_image_test.go

fix(build-image-tests): misplaced parameter removed #639

---

k2s/cmd/k2s/cmd/node/copy/copy.go
k2s/internal/core/node/copy/copy.go
k2s/internal/core/node/node.go
k2s/test/e2e/cli/cmd/node/setuprequired/systemrunning/copy/copy_system-running_test.go

feat(node-copy): copy from Linux nodes #639

---

k2s/test/e2e/addons/generic/build_image/build_image_test.go
lib/scripts/k2s/image/Build-Image.ps1

fix(tests): build image tests

---

k2s/cmd/k2s/cmd/node/copy/copy.go
k2s/internal/core/config/config.go
k2s/internal/core/node/copy/copy.go
k2s/internal/core/node/node.go
k2s/internal/core/node/ssh/ssh.go
k2s/internal/core/node/ssh/ssh_test.go
k2s/internal/host/host.go
k2s/internal/host/host_test.go
k2s/test/e2e/cli/cmd/node/setuprequired/systemrunning/copy/copy_system-running_test.go

feat(node-copy): copy from Windows nodes #639

---

k2s/test/e2e/cli/cmd/node/nosetup/corruptedstate/node_corrupted-state_test.go
k2s/test/e2e/cli/cmd/node/nosetup/node_no-setup_test.go
k2s/test/e2e/cli/cmd/node/setuprequired/systemstopped/copy/copy_system-stopped_test.go

fix(node-copy-tests): mandatory flag added to e2e tests #639

---

lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/httpproxy/httpproxy.module.psm1

fix(httpproxy): add .local to NO_PROXY

fix(httpproxy): add .local to NO_PROXY

---

k2s/test/e2e/cli/cmd/node/setuprequired/systemrunning/copy/copy_system-running_test.go

chore(node-copy-tests): disable winnode tests temporarily #639

---

lib/modules/k2s/k2s.infra.module/config/file.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/network/network.module.psm1

API for add & remove VFP routes

feat(network): API for VFP routes

---

lib/modules/k2s/k2s.infra.module/config/cluster.config.module.psm1

feat(node): API for node config

---

k2s/cmd/k2s/cmd/node/remove/remove.go
lib/modules/k2s/k2s.infra.module/config/cluster.config.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/worker-node.module.psm1
lib/scripts/worker-node/linux/bare-metal/Remove.ps1

Enabling remove node API for k2s cluster

feat(node): enabling remove node API

---

lib/modules/k2s/k2s.infra.module/config/cluster.config.module.psm1
lib/modules/k2s/k2s.infra.module/config/file.module.psm1

Configuration of node lifecycle improvements

feat(node): config improvements

---

lib/modules/k2s/k2s.node.module/linuxnode/setup/worker-node.module.psm1
lib/scripts/worker-node/linux/bare-metal/Add.ps1
lib/scripts/worker-node/linux/bare-metal/Remove.ps1

feat(node): basic logging

---

k2s/internal/core/clusterconfig/clusterconfig.go

feat(node): added cluster config

---

k2s/cmd/k2s/cmd/start/start.go
k2s/cmd/k2s/cmd/stop/stop.go

Enable stop of additional nodes in CLI

feat(node): enabling stop

---

build/bom/merge/k2s-static.json
k2s/test/e2e/cluster/core/core_test.go
k2s/test/framework/k8s/k8s.go
lib/modules/k2s/k2s.node.module/linuxnode/setup/control-plane-node.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/worker-node.module.psm1
lib/modules/k2s/k2s.node.module/vmnode/vmnode.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/containerd/containerd.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/docker/docker.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/windows-worker-node.module.psm1

feat(network): #847 internet connection speed improvements

feat(network): #847 internet connection speed improvements

---

k2s/cmd/k2s/cmd/stop/stop.go
lib/modules/k2s/k2s.node.module/linuxnode/setup/worker-node.module.psm1
lib/scripts/worker/linux/bare-metal/Start.ps1
lib/scripts/worker/linux/bare-metal/Stop.ps1

Some cleanup and changed order of stop due to dependencies.

feat(node): cleanup in start stop

---

addons/ingress/traefik/manifests/deployment.yaml

fix(addons): use traefik image from aws

fix(addons): use traefik image from aws

---

addons/ingress/nginx/Enable.ps1

fix(addons): increase timeout for ingress nginx admission webhook

fix(addons): increase timeout for ingress nginx admission webhook

---

lib/modules/k2s/k2s.node.module/linuxnode/setup/worker-node.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/network/network.module.psm1

fix(node): corrected route priority

---

docs/op-manual/extending-k2s-cluster.md

feat(node): doc for cluster extension

---

mkdocs.yml

chore(mkdocs): added cluster extension

---

k2s/cmd/k2s/cmd/addons/export/export.go
k2s/cmd/k2s/cmd/addons/importcmd/importcmd.go

feat(help): Correct help on export and import #780

feat(help): Correct help on export and import #780

---

k2s/cmd/k2s/cmd/stop/stop.go
lib/modules/k2s/k2s.cluster.module/system/system.module.psm1
lib/modules/k2s/k2s.infra.module/config/cluster.config.module.psm1
lib/scripts/worker/linux/bare-metal/Add.ps1

Add node without hostname input

39 node withoutname

---

lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1

retry coredns deployment update

39 coredns retry

---

docs/op-manual/extending-k2s-cluster.md

feat(doc): removed hostname flag

---

k2s/cmd/k2s/cmd/node/exec/exec.go
k2s/cmd/k2s/cmd/node/node.go
k2s/internal/core/node/node.go
k2s/test/e2e/cli/cmd/node/nosetup/corruptedstate/node_corrupted-state_test.go
k2s/test/e2e/cli/cmd/node/nosetup/node_no-setup_test.go
k2s/test/e2e/cli/cmd/node/setuprequired/systemrunning/exec/exec_system-running_test.go
k2s/test/e2e/cli/cmd/node/setuprequired/systemstopped/node_system-stopped_test.go

feat(node-exec): execute remote command #854

---

k2s/cmd/k2s/cmd/node/connect/connect.go
k2s/cmd/k2s/cmd/node/node.go
k2s/internal/core/node/node.go
k2s/test/e2e/cli/cmd/node/nosetup/corruptedstate/node_corrupted-state_test.go
k2s/test/e2e/cli/cmd/node/nosetup/node_no-setup_test.go
k2s/test/e2e/cli/cmd/node/setuprequired/systemrunning/connect/connect_system-running_test.go
k2s/test/e2e/cli/cmd/node/setuprequired/systemrunning/exec/exec_system-running_test.go
k2s/test/e2e/cli/cmd/node/setuprequired/systemstopped/node_system-stopped_test.go

feat(node-connect): interactive SSH session #855

---

k2s/test/e2e/cli/cmd/node/setuprequired/systemrunning/connect/connect_system-running_test.go

fix(node-connect-test): sut path fixed #855

---

k2s/cmd/k2s/cmd/node/connect/connect.go
k2s/cmd/k2s/cmd/system/scp/scp.go
k2s/cmd/k2s/cmd/system/ssh/master.go
k2s/cmd/k2s/cmd/system/ssh/worker.go
k2s/test/e2e/cli/cmd/node/setuprequired/systemrunning/connect/connect_system-running_test.go
k2s/test/e2e/cli/cmd/system/setuprequired/systemstopped/system_system-stopped_test.go

856-deprecate

---

k2s/test/e2e/cli/cmd/node/setuprequired/systemrunning/connect/connect_system-running_test.go

fix(node-connect-test): test to be manually executed #855

---

addons/logging/Disable.ps1
addons/logging/manifests/logging/fluentbit/windows/configmap-windows.yaml
addons/logging/manifests/logging/fluentbit/windows/daemonset-windows.yaml
k2s/test/e2e/addons/logging/logging_test.go

fix(addons): fix labeling of fluent-bit daemonsets

fix(addons): fix labeling of fluent-bit daemonsets

---

docs/op-manual/installing-k2s.md
k2s/test/e2e/cli/cmd/system/setuprequired/systemrunning/scp/scp_systemrunning_test.go

#907 test runs stability

---

docs/op-manual/installing-k2s.md
k2s/test/e2e/cli/cmd/system/setuprequired/systemrunning/scp/scp_systemrunning_test.go

#907 test runs stability: spelling error

#907 test runs stability: spelling error

---

.gitignore
k2s/test/e2e/cluster/node/node_test.go
k2s/test/framework/k8s/k8s.go

e2e test for n-nodes communication test

feat(node): e2e test for nodes

---

lib/modules/k2s/k2s.infra.module/config/cluster.config.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/worker-node.module.psm1

Proxy information will be useful for containers running on the node, how to connect to internet.
E.g k2s host, kubemaster -> Proxy is http://172.19.1.1:8181
New node -> Proxy is http://1.12.2.2:8080

feat(node): store proxy info

---

k2s/test/e2e/cluster/node/node_test.go

Minor improvements in node e2e

feat(e2e): node test improvements

---

k2s/internal/core/clusterconfig/clusterconfig.go
lib/modules/k2s/k2s.infra.module/config/cluster.config.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/worker-node.module.psm1
lib/scripts/worker/linux/bare-metal/Add.ps1
lib/scripts/worker/linux/bare-metal/Start.ps1

- Start additional nodes independent of Master node(Kubemaster).
- Cache PodCIDR during node addition and resuse during subsequent start/stop of nodes

feat(node): start node improvements

---

k2s/cmd/k2s/cmd/node/connect/connect.go
k2s/cmd/k2s/cmd/node/copy/copy.go
k2s/internal/core/node/connect.go
k2s/internal/core/node/copy.go
k2s/internal/core/node/exec.go
k2s/internal/core/node/ssh/keygen/keygen.go
k2s/internal/core/node/ssh/keygen/keygen_test.go
k2s/internal/core/users/add.go
k2s/internal/core/users/k8s/k8s.go
k2s/internal/core/users/k8s/k8s_test.go
k2s/internal/core/users/nodes/nodes.go
k2s/internal/core/users/nodes/nodes_test.go
k2s/internal/core/users/users.go

refactor(node-pkg): node operations re-structured #923

---

cfg/config.json
lib/modules/k2s/k2s.cluster.module/image/registry/registry.module.psm1
lib/modules/k2s/k2s.infra.module/config/config.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
lib/scripts/worker/windows/windows-host/Install.ps1

feat(mirror): #921 mirror registry for provisioning VM

feat(mirror): #921 mirror registry for provisioning VM

---

k2s/cmd/k2s/cmd/install/core/installer.go
k2s/cmd/k2s/cmd/install/install.go
k2s/cmd/k2s/cmd/system/upgrade/upgrade.go
k2s/internal/core/setupinfo/setupinfo.go
k2s/internal/core/setupinfo/setupinfo_test.go

refactor(setupinfo): read/write separation #923

---

lib/modules/k2s/k2s.infra.module/network/windows-host-network.module.psm1

fix(network): ensure reset of dns of network adapter

fix(network): ensure reset of dns of network adapter

---

k2s/cmd/k2s/cmd/system/users/add.go
k2s/internal/core/users/controlplane/controlplane.go
k2s/internal/core/users/controlplane/controlplane_test.go
k2s/internal/core/users/k8s/k8s.go
k2s/internal/core/users/k8s/k8s_test.go
k2s/internal/core/users/users.go

refactor(system-users): ssh access simplified #923

---

k2s/cmd/k2s/cmd/node/add/add.go
k2s/cmd/k2s/cmd/node/remove/remove.go

Added shorthand flags for node command operations

feat(cli): shorthand flags node cmd

---

k2s/test/e2e/addons/viewer/viewer_test.go

feat(addons): #802 addons viewer fixes (#948)

---

k2s/cmd/k2s/cmd/install/core/installer.go
k2s/internal/core/setupinfo/setupinfo.go
k2s/internal/powershell/exec.go

feat(install): output verbosity consolidated #965

---

k2s/test/framework/http/http.go
k2s/test/framework/k8s/k8s.go
k2s/test/framework/suite.go

refactor(e2e): resilient curl/rest calls #907

---

k2s/test/e2e/addons/registry/registry_test.go
k2s/test/framework/http/http.go

refactor(e2e-registry-addon): resilient http GET #907

---

build/bom/merge/k2s-static.json
lib/modules/k2s/k2s.infra.module/network/windows-host-network.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/network/network.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/control-plane-node.module.psm1
lib/modules/k2s/k2s.node.module/vmnode/vmnode.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/dnsproxy/dnsproxy.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/network/loopbackadapter.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/network/network.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/windows-worker-node.module.psm1
lib/scripts/control-plane/Start.ps1
lib/scripts/control-plane/Stop.ps1

#966 slower internet connectivity: refactor DNS functionality

#966 slower internet connectivity: refactor DNS functionality

---

lib/modules/k2s/k2s.node.module/windowsnode/network/network.module.psm1

If the creation of cbr0 fails for some reason due to an instability in HNS implementation, then the HNS service is restarted and cbr0 switch creation is retried until it succeeds, within a timeout of 10 minutes.

fix: improve l2 bridge creation

---

lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1

Issue with downloading  kubernetes artifacts in Debian 12
Fix the above issue.
Modification made in ~\K2s\lib\modules\k2s\k2s.node.module\linuxnode\distros\common-setup.module.psm1
Local K2S installation with Zscaler enabled worked fine.

Add ZscalerCertifcate prior to Kubernetes  artifact download

---

docs/dev-guide/contributing/powershell-dev.md
docs/dev-guide/contributing/tags-labels.md
docs/op-manual/installing-k2s.md
docs/user-guide/hosting-variants.md
k2s/cmd/k2s/cmd/install/config/config.go
k2s/cmd/k2s/cmd/install/install.go

feat(core): #907 tests stability: remove multivm on high level

feat(core): #907 tests stability: remove multivm on high level

---

lib/modules/k2s/k2s.node.module/linuxnode/setup/control-plane-node.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/setup/worker-node.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/baseimage/windows-provisioning.module.psm1
lib/scripts/k2s/system/package/New-K2sPackage.ps1

feat(core): #907 decrease disk space needs

feat(core): #907 decrease disk space needs

---

docs/op-manual/installing-k2s.md

docs: update variants entries for 1.3.0

docs: update variants entries for 1.3.0

---

addons/security/Enable.ps1
addons/security/security.module.psm1

feat(addons): #1037 enable enhanced security for linux only

feat(addons): #1037 enable enhanced security for linux only

---

.gitignore
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/helm/helm.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/downloader.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1

feat(core): #1048 add helm to k2s

feat(core): #1048 add helm to k2s

---

addons/ingress/traefik/manifests/cluster-local-ingress.yaml
addons/monitoring/manifests/monitoring/plutono/configmap.yaml
addons/security/manifests/keycloak/oauth2-proxy.yaml
addons/viewer/manifests/ingress-nginx/viewer-ingress-nginx.yaml
k2s/test/e2e/addons/autoscaling/autoscaling_test.go
k2s/test/e2e/addons/autoscaling_sec_test/autoscaling_sec_test.go
k2s/test/e2e/addons/dashboard_sec_test/dashboard_sec_test.go
k2s/test/e2e/addons/dicom_sec_test/dicom_sec_test.go
k2s/test/e2e/addons/ingress-nginx_sec_test/ingress-nginx_sec_test.go
k2s/test/e2e/addons/ingress-traefik_sec_test/ingress-traefik_sec_test.go
k2s/test/e2e/addons/ingress/nginx/workloads/ingress-nginx-test-linux-albums.yaml
k2s/test/e2e/addons/ingress/traefik/workloads/ingress-traefik-test-linux-albums.yaml
k2s/test/e2e/addons/logging_sec_test/logging_sec_test.go
k2s/test/e2e/addons/metrics_sec_test/metrics_sec_test.go
k2s/test/e2e/addons/monitoring_sec_test/monitoring_sec_test.go
k2s/test/e2e/addons/security/security_test.go
k2s/test/e2e/addons/viewer_sec_test/viewer_sec_test.go
k2s/test/framework/k2s/addons/addons.go

#258 added tests for enhanced security

feat(addons): #258 added tests for enhanced security

---

k2s/go.mod
k2s/go.sum

chore(deps): bump golang.org/x/oauth2 #1058

---

.github/workflows/build-k2s-artifacts.yml
.github/workflows/build-k2s-cli.yml
.github/workflows/ci-unit-tests.yml
lib/modules/k2s/k2s.node.module/linuxnode/distros/scripts/install_go.sh
lib/scripts/k2s/image/Build-Image.ps1

chore(deps): bump to Go v1.24.2 #1041

---

build/bom/merge/k2s-static.json
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/containerd/containerd.module.psm1

feat(core): #1057 increase containerd to 1.7.27

feat(core): #1057 increase containerd to 1.7.27 

---

build/bom/images/static-images.txt
build/bom/merge/k2s-static.json
lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/distros/containernetwork/masternode/flannel.template.yml
lib/modules/k2s/k2s.node.module/linuxnode/distros/containernetwork/masternode/flannel.yml
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/flannel/flannel.module.psm1

feat(core): #1056 upgrade to flannel 0.26.7

feat(core): #1056 upgrade to flannel 0.26.7

---

cfg/applocker/applockerrules.xml
lib/modules/k2s/k2s.node.module/windowsnode/downloader/downloader.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/setup/setupwinnode.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/system/system.module.psm1

feat(core): #1067 add applocker rule

feat(core): #1067 add applocker rule

---

k2s/internal/containernetworking/hnsproxy.go

fix(bridge): config/code mismatch #1083

---

build/bom/images/static-images.txt
build/bom/merge/k2s-static.json
lib/modules/k2s/k2s.infra.module/config/config.module.psm1

feat(core): #1071 increase K8s version to 1.32.5

feat(core): #1071 increase K8s version to 1.32.5

---

k2s/cmd/k2s/cmd/system/upgrade/upgrade.go
lib/modules/k2s/k2s.cluster.module/upgrade/upgrade.module.psm1
lib/modules/k2s/k2s.cluster.module/upgrade/upgrade.module.unit.tests.ps1
lib/scripts/k2s/system/upgrade/Start-ClusterUpgrade.ps1

#1076 implemented upgrade force

feat(core): #1076 implemented upgrade force

---

addons/storage/smb/module/Smb-share.module.psm1

fix(smb-addon): non-existent flag #1097

---

k2s/cmd/httpproxy/main.go
lib/scripts/k2s/system/shutdown/Stop-System.ps1
lib/scripts/k2s/system/startup/Start-System.ps1

feat(core): #1043 improve handling of shutdown

feat(core): #1043 improve handling of shutdown

---

k2s/cmd/k2s/cmd/system/certificate/certificate.go
k2s/cmd/k2s/cmd/system/certificate/renew.go
k2s/cmd/k2s/cmd/system/system.go
lib/modules/k2s/k2s.cluster.module/runningstate/runningstate.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/vm/vm.module.psm1
lib/scripts/k2s/system/certificate/renew.ps1

Adding the source code for missing cli option to renew certificates

feat(certificates): #981 cert renew command

---

addons/storage/smb/README.md

Update README.md as per new implementation of multiple folders

---

docs/troubleshooting/known-issues.md
lib/modules/k2s/k2s.node.module/windowsnode/downloader/downloader.module.psm1

feat(applocker): #1121 disable automatic applocker rules

feat(applocker): #1121 disable automatic applocker rules 

---

lib/modules/k2s/k2s.infra.module/log/log.module.psm1

redact token and hash value

---

addons/security/Enable.ps1
addons/security/security.module.psm1

feat(addons): #1105 correct usage of kubectl in security addon

feat(addons): #1105 correct usage of kubectl in security addon

---

lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1

feat(core): #1124 improve coredns patching

feat(core): #1124 improve coredns patching

---

k2s/cmd/k2s/cmd/system/users/add.go
k2s/internal/core/users/common/common.go
k2s/internal/core/users/k8s/kubeconfig/kubeconfig.go
k2s/internal/core/users/k8s/kubeconfig/kubeconfig_test.go
k2s/internal/core/users/k8s/kubectl/kubectl.go
k2s/internal/core/users/users.go
k2s/internal/core/users/users_test.go
k2s/internal/logging/logging_suite_test.go
k2s/test/e2e/cli/cmd/system/setuprequired/system_setup-required_test.go
k2s/test/e2e/cli/cmd/system/setuprequired/systemrunning/users/users_systemrunning_test.go

fix(system-users): kubectl exec with abs path #1119

---

addons/addons.module.psm1
addons/storage/addon.manifest.yaml
addons/storage/smb/Disable.ps1
addons/storage/smb/config/SmbStorage.json
addons/storage/smb/module/Smb-share.module.psm1
k2s/test/e2e/addons/storage/smb/storage-smb_test.go

feat(addons): #1141 storage addon improvements

feat(addons): #1141 storage addon improvements

---

k2s/internal/powershell/decode/decode.go
k2s/internal/powershell/decode/decode_test.go
k2s/internal/powershell/powershell.go
k2s/internal/powershell/powershell_test.go
lib/modules/k2s/k2s.infra.module/cli-messages/cli-messages.module.psm1
lib/modules/k2s/k2s.infra.module/cli-messages/cli-messages.module.unit.tests.ps1

fix(cli-messaging): payload chunked instead of limited #1155

---

build/bom/images/static-images.txt
build/bom/merge/k2s-static.json
lib/modules/k2s/k2s.cluster.module/setup/setupcluster.module.psm1
lib/modules/k2s/k2s.infra.module/config/config.module.psm1
lib/modules/k2s/k2s.node.module/linuxnode/distros/common-setup.module.psm1

#1159 increase k8s version to newest

#1159 increase k8s version to newest

---

build/bom/merge/k2s-static.json
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/containerd/containerd.module.psm1

#1162 feat(core): increase containerd to v2.1.3

#1162 feat(core): increase containerd to v2.1.3

---

addons/security/Disable.ps1
addons/security/Enable.ps1
addons/security/Get-Status.ps1
addons/security/README.md
addons/security/addon.manifest.yaml
addons/security/security.module.psm1
k2s/test/e2e/addons/security/security_test.go

feat(addon):#1250 added omit oauth2 in security addon

---

bin/windows_exporter.yaml
build/bom/merge/k2s-static.json
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/containerd/containerd.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/dnsproxy/dnsproxy.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/docker/docker.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/helm/helm.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/windows-exporter/windows-exporter.module.psm1
lib/modules/k2s/k2s.node.module/windowsnode/downloader/artifacts/yaml-tools/yaml-tools.module.psm1
test/execute_all_tests.ps1

#1254 update of all executables to newest version

#1254 update of all executables to newest version

---

build/bom/DumpK2sImages.ps1

Fixes #1099 
To include container images as part of helm chart content as part of SBOM.
Have extended existing logic in Dumpk2sImages.ps1 to collect container image references from helm chart files as well.
As DumpK2sImages.ps1 can be executed as standalone script using .\build\bom\Dumpk2sImages.ps1 .. Have verified the container-images-used.json file whether it contains container image references of values.yaml.
Looks like values.yaml is only present as part of dashboard addon only as of now.

Fixes Issue #1099 - Added changes to collect helm chart content as part of SBOM.
